use crate::VERSION;
use crate::frontend::ast::*;
use crate::frontend::{Cst, NodeRef};
use crate::frontend::sema::*;
use proc_macro2::TokenStream;
use quote::quote;
use rustc_hash::{FxHashMap, FxHashSet};
use std::collections::{BTreeMap, BTreeSet};
use std::io::{BufWriter, Write};
use std::path::Path;

pub fn snake_to_pascal_case(name: &str) -> String {
    let mut res = String::new();
    let mut upper = true;
    for c in name.chars() {
        if upper {
            res.push(c.to_ascii_uppercase());
            upper = false;
        } else if c == '_' {
            upper = true;
        } else {
            res.push(c);
        }
    }
    res
}

fn format_rust_source(source: &str) -> String {
    let file = syn::parse_file(source).expect("generated code should be valid Rust");
    prettyplease::unparse(&file)
}

fn gen_pattern(tokens: &BTreeSet<TokenName<'_>>) -> TokenStream {
    let idents: Vec<_> = tokens
        .iter()
        .map(|s| {
            let ident = proc_macro2::Ident::new(&s.0, proc_macro2::Span::call_site());
            quote!(Token::#ident)
        })
        .collect();
    quote!(#(#idents)|*)
}

fn gen_error_message<'a>(
    tokens: &BTreeSet<TokenName<'a>>,
    token_symbols: &FxHashMap<&str, &str>,
) -> TokenStream {
    let expected: Vec<_> = tokens
        .iter()
        .filter_map(|s| token_symbols.get(s.0.as_ref()))
        .map(|sym| {
            if sym.starts_with('<') && sym.ends_with('>') && sym.len() > 2 {
                sym.to_string()
            } else {
                format!("'{}'", sym)
            }
        })
        .collect();
    gen_syntax_error_message(&expected)
}

fn gen_syntax_error_message(expected: &[String]) -> TokenStream {
    let msg = if expected.is_empty() {
        "invalid syntax".to_string()
    } else if expected.len() == 1 {
        format!("invalid syntax, expected: {}", expected[0])
    } else {
        format!("invalid syntax, expected one of: {}", expected.join(", "))
    };
    let unescaped = msg.replace(r"\\", r"\").replace(r"\'", "'");
    quote!(#unescaped)
}

fn self_ident() -> proc_macro2::Ident {
    quote::format_ident!("self")
}

fn parser_ident() -> proc_macro2::Ident {
    quote::format_ident!("parser")
}

fn snake_to_pascal_case_ident(name: &str) -> proc_macro2::Ident {
    quote::format_ident!("{}", snake_to_pascal_case(name))
}

pub struct RustOutput {}

impl RustOutput {
    pub fn run(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        input: &Path,
        output: &Path,
    ) -> std::io::Result<()> {
        let file = File::cast(cst, NodeRef::ROOT).unwrap();
        let generated_tokens = Self::gen_generated(cst, sema, file);
        let generated_source = format!("// generated by lelwel {VERSION}\n\n{generated_tokens}");
        let formatted = format_rust_source(&generated_source);
        let mut generated_file =
            BufWriter::new(std::fs::File::create(output.join("generated.rs"))?);
        generated_file.write_all(formatted.as_bytes())?;

        let parser_path = input.parent().unwrap().join("parser.rs");
        let lexer_path = input.parent().unwrap().join("lexer.rs");
        if !parser_path.exists() && !lexer_path.exists() {
            let parser_source = Self::gen_parser(sema).to_string();
            let parser_formatted = format_rust_source(&parser_source);
            std::fs::write(&parser_path, parser_formatted)?;

            let lexer_source = Self::gen_lexer(cst, file).to_string();
            let lexer_formatted = format_rust_source(&lexer_source);
            std::fs::write(&lexer_path, lexer_formatted)?;
        }
        Ok(())
    }

    fn gen_parser(sema: &SemanticData<'_>) -> TokenStream {
        let callbacks = Self::gen_parser_callbacks(sema, false, BTreeMap::default());
        quote! {
            use lelwel::{ParserHooks, Parser, Span, Cst, NodeRef};
            use super::lexer::{Token, tokenize};
            use codespan_reporting::diagnostic::Label;
            pub type Diagnostic = codespan_reporting::diagnostic::Diagnostic<()>;
            include!(concat!(env!("OUT_DIR"), "/generated.rs"));
            #callbacks
        }
    }

    fn gen_lexer(cst: &Cst<'_>, file: File) -> TokenStream {
        let mut token_variants = Vec::new();
        token_variants.push(quote! { EOF });
        for token in file.token_decls(cst) {
            if let Some((symbol, _)) = token.symbol(cst)
                && !symbol.is_empty()
                && !(symbol.starts_with("'<") && symbol.ends_with(">'") && symbol.len() > 4)
            {
                let token_str = &symbol[1..symbol.len() - 1];
                let name = proc_macro2::Ident::new(
                    token.name(cst).unwrap().0,
                    proc_macro2::Span::call_site(),
                );
                token_variants.push(quote! { #[token(#token_str)] #name });
                continue;
            }
            let name =
                proc_macro2::Ident::new(token.name(cst).unwrap().0, proc_macro2::Span::call_site());
            token_variants.push(quote! { #name });
        }
        token_variants.push(quote! { Error });
        quote! {
            use lelwel::Span;
            use super::parser::Diagnostic;
            use codespan_reporting::diagnostic::Label;
            use logos::Logos;

            #[derive(Debug, Clone, PartialEq, Default)]
            pub enum LexerError {
                #[default]
                Invalid,
            }

            impl LexerError {
                pub fn into_diagnostic(self, span: Span) -> Diagnostic {
                    match self {
                        Self::Invalid => Diagnostic::error()
                            .with_message("invalid token")
                            .with_label(Label::primary((), span)),
                    }
                }
            }

            #[allow(clippy::upper_case_acronyms)]
            #[derive(Logos, Debug, PartialEq, Eq, Copy, Clone)]
            #[logos(error = LexerError)]
            pub enum Token {
                #(#token_variants)*
            }

            pub fn tokenize(
                source: &str,
                diags: &mut Vec<Diagnostic>,
            ) -> (Vec<Token>, Vec<Span>) {
                let lexer = Token::lexer(source);
                let mut tokens = vec![];
                let mut spans = vec![];

                for (token, span) in lexer.spanned() {
                    match token {
                        Ok(token) => {
                            tokens.push(token);
                        }
                        Err(err) => {
                            diags.push(err.into_diagnostic(span.clone()));
                            tokens.push(Token::Error);
                        }
                    }
                    spans.push(span);
                }
                (tokens, spans)
            }
        }
    }

    fn gen_parser_callbacks(
        sema: &SemanticData<'_>,
        is_trait: bool,
        rule_names: BTreeMap<&str, bool>,
    ) -> TokenStream {
        if is_trait {
            let mut create_node_methods = Vec::new();
            for rule_name in rule_names.keys() {
                let create_fn = quote::format_ident!("create_node_{}", rule_name);
                let doc = format!("Called when `{rule_name}` node is created.");
                create_node_methods.push(quote! {
                    #[doc = #doc]
                    fn #create_fn(&mut self, _node_ref: NodeRef, _diags: &mut Vec<Self::Diagnostic>) {}
                });
            }

            let mut delete_node_methods = Vec::new();
            for (rule_name, in_choice) in &rule_names {
                if *in_choice {
                    let delete_fn = quote::format_ident!("delete_node_{}", rule_name);
                    let doc =
                        format!("Called when `{rule_name}` node is deleted during backtracking.");
                    delete_node_methods.push(quote! {
                        #[doc = #doc]
                        fn #delete_fn(&mut self, _node_ref: NodeRef) {}
                    });
                }
            }

            let mut predicate_methods = Vec::new();
            let mut seen_predicates = FxHashSet::default();
            for (rule, num) in sema.predicates.values() {
                if seen_predicates.contains(&(rule, num)) {
                    continue;
                }
                seen_predicates.insert((rule, num));
                let pred_fn = quote::format_ident!("predicate_{}_{}", rule, num);
                let doc =
                    format!("Called when semantic predicate `?{num}` in rule `{rule}` is visited.");
                predicate_methods.push(quote! {
                    #[doc = #doc]
                    fn #pred_fn(&self) -> bool;
                });
            }

            let mut action_methods = Vec::new();
            let mut seen_actions = FxHashSet::default();
            for (rule, num) in sema.actions.values() {
                if seen_actions.contains(&(rule, num)) {
                    continue;
                }
                seen_actions.insert((rule, num));
                let action_fn = quote::format_ident!("action_{}_{}", rule, num);
                let doc =
                    format!("Called when semantic action `#{num}` in rule `{rule}` is visited.");
                action_methods.push(quote! {
                    #[doc = #doc]
                    fn #action_fn(&mut self, diags: &mut Vec<Self::Diagnostic>);
                });
            }

            let mut assertion_methods = Vec::new();
            let mut seen_assertions = FxHashSet::default();
            for (rule, num) in sema.assertions.values() {
                if seen_assertions.contains(&(rule, num)) {
                    continue;
                }
                seen_assertions.insert((rule, num));
                let assert_fn = quote::format_ident!("assertion_{}_{}", rule, num);
                let doc =
                    format!("Called when semantic assertion `!{num}` in rule `{rule}` is visited.");
                assertion_methods.push(quote! {
                    #[doc = #doc]
                    fn #assert_fn(&self) -> Option<Self::Diagnostic>;
                });
            }

            let create_tokens_doc =
                "Called at the start of the parse to generate all tokens and corresponding spans.";
            let create_diagnostic_doc = "Called when diagnostic is created.";
            let predicate_skip_doc = "This predicate can be used to skip normal tokens.";

            quote! {
                #[allow(clippy::ptr_arg)]
                pub trait ParserCallbacks<'a>: ParserHooks<'a, Token, Rule, Diag = Self::Diagnostic, Ctx = Self::Context> {
                    type Diagnostic;
                    type Context;

                    #[doc = #create_tokens_doc]
                    fn create_tokens(context: &mut Self::Context, source: &'a str, diags: &mut Vec<Self::Diagnostic>) -> (Vec<Token>, Vec<Span>);
                    #[doc = #create_diagnostic_doc]
                    fn create_diagnostic(&self, span: Span, message: String) -> Self::Diagnostic;
                    #[doc = #predicate_skip_doc]
                    fn predicate_skip(&self, _token: Token) -> bool {
                        false
                    }

                    #(#create_node_methods)*

                    #(#delete_node_methods)*

                    #(#predicate_methods)*

                    #(#action_methods)*

                    #(#assertion_methods)*
                }
            }
        } else {
            let mut predicate_methods = Vec::new();
            let mut seen_predicates = FxHashSet::default();
            for (rule, num) in sema.predicates.values() {
                if seen_predicates.contains(&(rule, num)) {
                    continue;
                }
                seen_predicates.insert((rule, num));
                let pred_fn = quote::format_ident!("predicate_{}_{}", rule, num);
                predicate_methods.push(quote! {
                    fn #pred_fn(&self) -> bool {
                        todo!()
                    }
                });
            }

            let mut action_methods = Vec::new();
            let mut seen_actions = FxHashSet::default();
            for (rule, num) in sema.actions.values() {
                if seen_actions.contains(&(rule, num)) {
                    continue;
                }
                seen_actions.insert((rule, num));
                let action_fn = quote::format_ident!("action_{}_{}", rule, num);
                action_methods.push(quote! {
                    fn #action_fn(&mut self, diags: &mut Vec<Self::Diagnostic>) {
                        todo!()
                    }
                });
            }

            let mut assertion_methods = Vec::new();
            let mut seen_assertions = FxHashSet::default();
            for (rule, num) in sema.assertions.values() {
                if seen_assertions.contains(&(rule, num)) {
                    continue;
                }
                seen_assertions.insert((rule, num));
                let assert_fn = quote::format_ident!("assertion_{}_{}", rule, num);
                assertion_methods.push(quote! {
                    fn #assert_fn(&self) -> Option<Self::Diagnostic> {
                        todo!()
                    }
                });
            }

            quote! {
                impl<'a> ParserCallbacks<'a> for Parser<'a, Token, Rule, ()> {
                    type Diagnostic = Diagnostic;
                    type Context = ();

                    fn create_tokens(_context: &mut Self::Context, source: &'a str, diags: &mut Vec<Self::Diagnostic>) -> (Vec<Token>, Vec<Span>) {
                        tokenize(source, diags)
                    }
                    fn create_diagnostic(&self, span: Span, message: String) -> Self::Diagnostic {
                        Self::Diagnostic::error()
                            .with_message(message)
                            .with_label(Label::primary((), span))
                    }

                    #(#predicate_methods)*

                    #(#action_methods)*

                    #(#assertion_methods)*
                }
            }
        }
    }

    fn gen_node_kind_decl(has_rule_rename: bool, name: &str, is_decl: bool) -> TokenStream {
        if !has_rule_rename {
            return TokenStream::new();
        }
        let variant = snake_to_pascal_case_ident(name);
        if is_decl {
            quote! { let mut node_kind = Rule::#variant; }
        } else {
            quote! { node_kind = Rule::#variant; }
        }
    }

    fn gen_cst_close(
        has_rule_rename: bool,
        name: &str,
        assign_lhs: bool,
        parser_name: &proc_macro2::Ident,
        is_start: bool,
    ) -> TokenStream {
        let close_method = if is_start {
            quote::format_ident!("close_root")
        } else {
            quote::format_ident!("close")
        };
        let variant = snake_to_pascal_case_ident(name);
        let close_and_create = if has_rule_rename {
            quote! {
                let closed = #parser_name.#close_method(m, node_kind, diags);
                #parser_name.create_node(node_kind, NodeRef(closed.0), diags);
            }
        } else {
            let create_node_method = quote::format_ident!("create_node_{}", name);
            quote! {
                let closed = #parser_name.#close_method(m, Rule::#variant, diags);
                #parser_name.#create_node_method(NodeRef(closed.0), diags);
            }
        };
        let assign = if assign_lhs {
            quote! { lhs = closed; }
        } else {
            TokenStream::new()
        };
        quote! {
            #close_and_create
            #assign
        }
    }

    fn gen_elision_init(
        has_rule_creation: bool,
        parser_name: &proc_macro2::Ident,
        is_start: bool,
        elision: RuleNodeElision,
    ) -> TokenStream {
        if is_start {
            return TokenStream::new();
        }
        match elision {
            RuleNodeElision::None => quote! {
                let m = #parser_name.open(diags);
            },
            RuleNodeElision::Conditional => quote! {
                let start = #parser_name.mark(diags);
                let mut elide = false;
            },
            RuleNodeElision::Unconditional => {
                if has_rule_creation {
                    quote! { let start = #parser_name.mark(diags); }
                } else {
                    TokenStream::new()
                }
            }
        }
    }

    fn gen_elision_check(
        has_rule_rename: bool,
        name: &str,
        parser_name: &proc_macro2::Ident,
        is_start: bool,
        elision: RuleNodeElision,
    ) -> TokenStream {
        if is_start {
            return TokenStream::new();
        }
        match elision {
            RuleNodeElision::None => {
                Self::gen_cst_close(has_rule_rename, name, false, parser_name, is_start)
            }
            RuleNodeElision::Conditional => {
                let close =
                    Self::gen_cst_close(has_rule_rename, name, false, parser_name, is_start);
                quote! {
                    if !elide {
                        let m = #parser_name.open_before(start, diags);
                        #close
                    }
                }
            }
            RuleNodeElision::Unconditional => TokenStream::new(),
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn gen_normal_rule(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        token_symbols: &FxHashMap<&str, &str>,
        has_rule_rename: bool,
        has_rule_creation: bool,
        name: &str,
        regex: Regex,
        is_start: bool,
        elision: RuleNodeElision,
    ) -> TokenStream {
        let elision_init =
            Self::gen_elision_init(has_rule_creation, &self_ident(), is_start, elision);
        let node_kind = if !is_start {
            Self::gen_node_kind_decl(has_rule_rename, name, true)
        } else {
            TokenStream::new()
        };
        let regex_code = Self::gen_regex(
            cst,
            sema,
            regex,
            token_symbols,
            false,
            name,
            elision,
            &self_ident(),
            has_rule_rename,
        );
        let elision_check =
            Self::gen_elision_check(has_rule_rename, name, &self_ident(), is_start, elision);
        quote! { #elision_init #node_kind #regex_code #elision_check }
    }

    #[allow(clippy::too_many_arguments)]
    fn gen_left_recursive_rule(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        token_symbols: &FxHashMap<&str, &str>,
        has_rule_rename: bool,
        name: &str,
        regex: Regex,
        recursive: &RecursiveBranches,
        in_choice: bool,
    ) -> TokenStream {
        let requires_bp = recursive.branches().len() > 1
            && recursive
                .branches()
                .iter()
                .any(|branch| matches!(branch, Recursion::Right(..) | Recursion::LeftRight(..)));
        let parser = parser_ident();
        let self_ = self_ident();
        let min_bp_param = if requires_bp {
            quote! { min_bp : usize , }
        } else {
            TokenStream::new()
        };
        let ret_type = if in_choice {
            quote! { -> Option < () > }
        } else {
            TokenStream::new()
        };
        let node_kind_decl = Self::gen_node_kind_decl(has_rule_rename, name, true);
        let ops: Vec<Regex> = if let Regex::Alternation(alt) = regex {
            alt.operands(cst).collect()
        } else {
            unreachable!()
        };
        let mut right_arms = Vec::new();
        let mut advance_error_set = BTreeSet::new();
        for alt_op in ops {
            let branch = recursive.get_branch(alt_op);
            if !matches!(branch, None | Some(Recursion::Right(..))) {
                continue;
            }
            let predict = &sema.predict_sets[&alt_op.syntax()];
            let predicate = Self::gen_predicate(cst, name, alt_op, &parser);
            advance_error_set = if predicate.is_none() {
                advance_error_set.difference(predict).cloned().collect()
            } else {
                advance_error_set.union(predict).cloned().collect()
            };
            let predict_pat = gen_pattern(predict);
            let elision = *sema.elision.get(&alt_op.syntax()).unwrap();
            let elision_init = Self::gen_elision_init(false, &parser, false, elision);
            let body = if let Some(Recursion::Right(_, index)) = branch {
                let bp = recursive.binding_power(alt_op).0;
                let Regex::Concat(concat) = alt_op else {
                    unreachable!()
                };
                let mut parts = Vec::new();
                for (i, concat_op) in concat.operands(cst).enumerate() {
                    if i == index {
                        let lhs_ident = quote::format_ident!("lhs");
                        let call = if requires_bp {
                            if in_choice {
                                quote! { rec ( #parser , diags , #bp , #lhs_ident ) ? ; }
                            } else {
                                quote! { rec ( #parser , diags , #bp , #lhs_ident ) ; }
                            }
                        } else if in_choice {
                            quote! { rec ( #parser , diags , #lhs_ident ) ? ; }
                        } else {
                            quote! { rec ( #parser , diags , #lhs_ident ) ; }
                        };
                        parts.push(quote! {
                            let lhs = #parser . mark ( diags ) ;
                            #call
                        });
                    } else {
                        parts.push(Self::gen_regex(
                            cst,
                            sema,
                            concat_op,
                            token_symbols,
                            false,
                            name,
                            elision,
                            &parser,
                            has_rule_rename,
                        ));
                    }
                }
                quote! { # ( #parts ) * }
            } else {
                Self::gen_regex(
                    cst,
                    sema,
                    alt_op,
                    token_symbols,
                    false,
                    name,
                    elision,
                    &parser,
                    has_rule_rename,
                )
            };
            let elision_check =
                Self::gen_elision_check(has_rule_rename, name, &parser, false, elision);
            let arm = match predicate {
                Some(pred) => quote! {
                    #predict_pat if #pred => {
                        #elision_init
                        #body
                        #elision_check
                    }
                },
                None => quote! {
                    #predict_pat => {
                        #elision_init
                        #body
                        #elision_check
                    }
                },
            };
            right_arms.push(arm);
        }
        let advance_error_arm = if !advance_error_set.is_empty() {
            let pattern = gen_pattern(&advance_error_set);
            let msg = gen_syntax_error_message(&[]);
            quote! {
                #pattern => {
                    #parser . advance_with_error ( diags , err ! [ #parser , #msg ] ) ;
                }
            }
        } else {
            TokenStream::new()
        };
        let expected = gen_error_message(&sema.predict_sets[&regex.syntax()], token_symbols);
        let wildcard_arm = quote! {
            _ => {
                #parser . error ( diags , err ! [ #parser , #expected ] ) ;
            }
        };
        let node_kind_assign = Self::gen_node_kind_decl(has_rule_rename, name, false);
        let mut left_arms = Vec::new();
        for branch in recursive.branches() {
            let (concat, left_index, right_index) = match branch {
                Recursion::Left(Regex::Concat(concat), index) => (concat, *index, None),
                Recursion::LeftRight(Regex::Concat(concat), left_index, right_index) => {
                    (concat, *left_index, Some(*right_index))
                }
                _ => continue,
            };
            let bp = recursive.binding_power(branch.regex());
            let pred = Self::gen_predicate(cst, name, branch.regex(), &parser);
            let mut first_predict = None;
            let mut bp_check = TokenStream::new();
            let mut body_parts = Vec::new();
            let mut is_first = true;
            for (i, concat_op) in concat.operands(cst).enumerate() {
                if let Regex::Predicate(..) = concat_op {
                    continue;
                }
                if i == left_index {
                    continue;
                }
                if is_first {
                    is_first = false;
                    first_predict = Some(gen_pattern(&sema.predict_sets[&concat_op.syntax()]));
                    if requires_bp {
                        let left_bp = bp.0;
                        bp_check = quote! { if #left_bp < min_bp { break ; } }
                    }
                    body_parts.push(quote! { let m = #parser . open_before ( lhs , diags ) ; });
                }
                if right_index == Some(i) {
                    let right_bp = bp.1;
                    let rhs_ident = quote::format_ident!("rhs");
                    let call = if requires_bp {
                        if in_choice {
                            quote! { rec ( #parser , diags , #right_bp , #rhs_ident ) ? ; }
                        } else {
                            quote! { rec ( #parser , diags , #right_bp , #rhs_ident ) ; }
                        }
                    } else if in_choice {
                        quote! { rec ( #parser , diags , #rhs_ident ) ? ; }
                    } else {
                        quote! { rec ( #parser , diags , #rhs_ident ) ; }
                    };
                    body_parts.push(quote! {
                        let rhs = #parser . mark ( diags ) ;
                        #call
                    });
                } else {
                    body_parts.push(Self::gen_regex(
                        cst,
                        sema,
                        concat_op,
                        token_symbols,
                        false,
                        name,
                        RuleNodeElision::None,
                        &parser,
                        has_rule_rename,
                    ));
                }
            }
            let close = Self::gen_cst_close(has_rule_rename, name, true, &parser, false);
            let predict_pat = first_predict.unwrap();
            let arm = match pred {
                Some(p) => quote! {
                    #predict_pat if #p => {
                        #bp_check
                        # ( #body_parts ) *
                        #close
                        continue ;
                    }
                },
                None => quote! {
                    #predict_pat => {
                        #bp_check
                        # ( #body_parts ) *
                        #close
                        continue ;
                    }
                },
            };
            left_arms.push(arm);
        }
        let some_return = if in_choice {
            quote! { Some ( () ) }
        } else {
            TokenStream::new()
        };
        let lhs_ident = quote::format_ident!("lhs");
        let outer_call = if requires_bp {
            if in_choice {
                quote! { rec ( #self_ , diags , 0 , #lhs_ident ) ? ; }
            } else {
                quote! { rec ( #self_ , diags , 0 , #lhs_ident ) ; }
            }
        } else if in_choice {
            quote! { rec ( #self_ , diags , #lhs_ident ) ? ; }
        } else {
            quote! { rec ( #self_ , diags , #lhs_ident ) ; }
        };
        let parser_ty = quote! { Parser < 'b , Token , Rule , Ctx > };
        let diags_ty = quote! { Vec < < #parser_ty as ParserCallbacks < 'b > > :: Diagnostic > };
        quote! {
            fn rec < 'b , Ctx > (
                parser : & mut #parser_ty ,
                diags : & mut #diags_ty ,
                #min_bp_param
                mut lhs : MarkClosed ,
            ) #ret_type
            where
                #parser_ty : ParserCallbacks < 'b > ,
                Ctx : From < < #parser_ty as ParserHooks < 'b , Token , Rule > > :: Ctx > ,
                < #parser_ty as ParserHooks < 'b , Token , Rule > > :: Ctx : From < Ctx > ,
            {
                #node_kind_decl
                match #parser . current {
                    # ( #right_arms ) *
                    #advance_error_arm
                    #wildcard_arm
                }
                loop {
                    #node_kind_assign
                    match #parser . current {
                        # ( #left_arms ) *
                        _ => {
                            break ;
                        }
                    }
                }
                #some_return
            }
            let #lhs_ident = #self_ . mark ( diags ) ;
            #outer_call
        }
    }

    fn gen_parts_sig(cst: &Cst<'_>, rule: RuleDecl) -> TokenStream {
        let name = rule.name(cst).unwrap().0;
        let parse_fn = quote::format_ident!("parse_{}", name);
        let doc = format!("Returns the CST for a parse of the {name} rule");
        quote! {
            #[doc = #doc]
            fn #parse_fn(self, diags: &mut Vec<Self::Diagnostic>) -> Cst<'a, Token, Rule>;
        }
    }

    fn gen_parts_impl(cst: &Cst<'_>, rule: RuleDecl) -> TokenStream {
        let name = rule.name(cst).unwrap().0;
        let parse_fn = quote::format_ident!("parse_{}", name);
        let eof_variant = quote::format_ident!("EOF{}", snake_to_pascal_case(name));
        quote! {
            fn #parse_fn(mut self, diags: &mut Vec<Self::Diagnostic>) -> Cst<'a, Token, Rule> {
                self.end_of_input = Token::#eof_variant;
                self.parse_with(|parser, diags| parser.rule_part(diags), diags, Rule::Part)
            }
        }
    }

    fn gen_rule_part(cst: &Cst<'_>, sema: &SemanticData<'_>) -> TokenStream {
        let mut arms = Vec::new();
        for part in &sema.parts {
            let name = part.name(cst).unwrap().0;
            let eof_variant = quote::format_ident!("EOF{}", snake_to_pascal_case(name));
            let rule_fn = quote::format_ident!("rule_{}", name);
            arms.push(quote! {
                Token::#eof_variant => self.#rule_fn(diags),
            });
        }
        quote! {
            fn rule_part(&mut self, diags: &mut Vec<Self::Diagnostic>) {
                match self.end_of_input {
                    #(#arms)*
                    _ => {}
                }
            }
        }
    }

    fn gen_rule(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        rule: RuleDecl,
        token_symbols: &FxHashMap<&str, &str>,
    ) -> TokenStream {
        if !sema.used.contains(&rule.syntax()) {
            return TokenStream::new();
        }
        let name = rule.name(cst).unwrap().0;
        let recursive = sema.recursive.get(&rule);
        let is_start = sema.start_rule.unwrap() == rule;
        let has_rule_rename = sema.has_rule_rename.contains(&rule);
        let has_rule_creation = sema.has_rule_creation.contains(&rule);
        let elision = if rule.is_elided(cst) {
            RuleNodeElision::Unconditional
        } else {
            rule.regex(cst)
                .and_then(|regex| sema.elision.get(&regex.syntax()))
                .copied()
                .unwrap_or(RuleNodeElision::None)
        };
        let in_choice = sema.used_in_ordered_choice.contains(&rule.syntax());
        let rule_fn = quote::format_ident!("rule_{}", name);
        let attr = if has_rule_rename {
            quote! { # [ allow ( unused_assignments ) ] }
        } else {
            TokenStream::new()
        };
        let ret_type = if in_choice {
            quote! { -> Option < () > }
        } else {
            TokenStream::new()
        };
        let body = if let Some(regex) = rule.regex(cst) {
            if recursive.is_some_and(|recursive| {
                recursive
                    .branches()
                    .iter()
                    .any(|rec| matches!(rec, Recursion::Left(..) | Recursion::LeftRight(..)))
            }) {
                Self::gen_left_recursive_rule(
                    cst,
                    sema,
                    token_symbols,
                    has_rule_rename,
                    name,
                    regex,
                    recursive.unwrap(),
                    in_choice,
                )
            } else {
                Self::gen_normal_rule(
                    cst,
                    sema,
                    token_symbols,
                    has_rule_rename,
                    has_rule_creation,
                    name,
                    regex,
                    is_start,
                    elision,
                )
            }
        } else {
            TokenStream::new()
        };
        let return_val = if in_choice {
            quote! { Some ( () ) }
        } else {
            TokenStream::new()
        };
        quote! {
            #attr
            fn #rule_fn ( & mut self , diags : & mut Vec < Self :: Diagnostic > ) #ret_type {
                #body
                #return_val
            }
        }
    }

    fn gen_predicate(
        cst: &Cst<'_>,
        rule_name: &str,
        regex: Regex,
        parser_name: &proc_macro2::Ident,
    ) -> Option<TokenStream> {
        match regex {
            Regex::Concat(concat) => match concat.operands(cst).next().unwrap() {
                Regex::Predicate(pred) => {
                    if pred.is_true(cst) {
                        Some(quote! { true })
                    } else {
                        let num = &pred.value(cst).unwrap().0[1..];
                        let method = quote::format_ident!("predicate_{}_{}", rule_name, num);
                        Some(quote! { #parser_name.#method() })
                    }
                }
                _ => None,
            },
            Regex::Paren(paren) => {
                if let Some(inner) = paren.inner(cst) {
                    Self::gen_predicate(cst, rule_name, inner, parser_name)
                } else {
                    None
                }
            }
            _ => None,
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn gen_recovering_operation(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        regex: Regex,
        token_symbols: &FxHashMap<&str, &str>,
        open_before: bool,
        rule_name: &str,
        rule_elision: RuleNodeElision,
        parser_name: &proc_macro2::Ident,
        has_rule_rename: bool,
        op: Regex,
        ordered_choice_return: TokenStream,
        is_loop: bool,
    ) -> TokenStream {
        let first_pattern = gen_pattern(&sema.first_sets[&op.syntax()]);
        let predicate = Self::gen_predicate(cst, rule_name, op, parser_name);
        let open_before_block = if open_before {
            quote! {
                if m.is_none() {
                    m = Some(#parser_name.open_before(lhs, diags));
                }
            }
        } else {
            TokenStream::new()
        };
        let body = Self::gen_regex(
            cst,
            sema,
            op,
            token_symbols,
            false,
            rule_name,
            rule_elision,
            parser_name,
            has_rule_rename,
        );
        let break_if_not_loop = if !is_loop {
            quote! { break; }
        } else {
            TokenStream::new()
        };
        let follow_pattern = gen_pattern(&sema.follow_sets[&regex.syntax()]);
        let expected = if is_loop {
            gen_error_message(&sema.follow_sets[&op.syntax()], token_symbols)
        } else {
            gen_error_message(&sema.predict_sets[&regex.syntax()], token_symbols)
        };
        let recovery = &sema.recovery_sets[&regex.syntax()];
        let recovery_arm = if recovery.is_empty() {
            TokenStream::new()
        } else {
            let recovery_pattern = gen_pattern(recovery);
            let ocr = ordered_choice_return.clone();
            quote! {
                | #recovery_pattern => {
                    #ocr
                    #parser_name.error(diags, err![#parser_name, #expected]);
                    break;
                }
            }
        };
        let ocr = ordered_choice_return;
        let first_arm = match predicate {
            Some(pred) => {
                quote! { #first_pattern if #pred => { #open_before_block #body #break_if_not_loop } }
            }
            None => quote! { #first_pattern => { #open_before_block #body #break_if_not_loop } },
        };
        quote! {
            loop {
                match #parser_name.current {
                    #first_arm
                    #follow_pattern => break,
                    #recovery_arm
                    _ => {
                        #ocr
                        #parser_name.advance_with_error(diags, err![#parser_name, #expected]);
                    }
                }
            }
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn gen_regex(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        regex: Regex,
        token_symbols: &FxHashMap<&str, &str>,
        open_before: bool,
        rule_name: &str,
        rule_elision: RuleNodeElision,
        parser_name: &proc_macro2::Ident,
        has_rule_rename: bool,
    ) -> TokenStream {
        let in_choice = sema.used_in_ordered_choice.contains(&regex.syntax());
        let expect_macro = if in_choice {
            quote::format_ident!("try_expect")
        } else {
            quote::format_ident!("expect")
        };
        let ordered_choice_return = if in_choice {
            quote! {
                if #parser_name.in_ordered_choice {
                    return None;
                }
            }
        } else {
            TokenStream::new()
        };
        match regex {
            Regex::Name(name) => {
                let decl = sema.decl_bindings[&name.syntax()];
                if let Some(rule) = RuleDecl::cast(cst, decl) {
                    let name = rule.name(cst).unwrap().0;
                    let rule_in_choice = sema.used_in_ordered_choice.contains(&rule.syntax());
                    let rule_fn = quote::format_ident!("rule_{}", name);
                    if rule_in_choice && in_choice {
                        quote! { #parser_name.#rule_fn(diags)?; }
                    } else {
                        quote! { #parser_name.#rule_fn(diags); }
                    }
                } else if let Some(token) = TokenDecl::cast(cst, decl) {
                    let name = token.name(cst).unwrap().0;
                    let sym = token
                        .symbol(cst)
                        .map_or(name, |(sym, _)| &sym[1..sym.len() - 1]);
                    let token_ident = quote::format_ident!("{}", name);
                    let error_msg = gen_syntax_error_message(&[sym.to_string()]);
                    quote! { #expect_macro!(#token_ident, #error_msg, #parser_name, diags); }
                } else {
                    TokenStream::new()
                }
            }
            Regex::Symbol(sym) => {
                let decl = sema.decl_bindings[&sym.syntax()];
                if let Some(token) = TokenDecl::cast(cst, decl) {
                    let name = token.name(cst).unwrap().0;
                    let sym_val = token.symbol(cst).unwrap().0;
                    let token_ident = quote::format_ident!("{}", name);
                    let error_msg = gen_syntax_error_message(&[sym_val.to_string()]);
                    quote! { #expect_macro!(#token_ident, #error_msg, #parser_name, diags); }
                } else {
                    TokenStream::new()
                }
            }
            Regex::Action(action) => {
                let num = &action.value(cst).unwrap().0[1..];
                let method = quote::format_ident!("action_{}_{}", rule_name, num);
                quote! { #parser_name.#method(diags); }
            }
            Regex::Assertion(assertion) => {
                let num = &assertion.value(cst).unwrap().0[1..];
                let method = quote::format_ident!("assertion_{}_{}", rule_name, num);
                let ocr = ordered_choice_return.clone();
                quote! {
                    if let Some(diag) = #parser_name.#method() {
                        #ocr
                        #parser_name.error_since_advance = true;
                        diags.push(diag);
                    }
                }
            }
            Regex::NodeRename(rename) => {
                let name = &rename.value(cst).unwrap().0[1..];
                if !name.is_empty() {
                    let variant = snake_to_pascal_case_ident(name);
                    quote! { node_kind = Rule::#variant; }
                } else {
                    TokenStream::new()
                }
            }
            Regex::NodeElision(_) => {
                if rule_elision == RuleNodeElision::Conditional {
                    quote! { elide = true; }
                } else {
                    TokenStream::new()
                }
            }
            Regex::NodeMarker(marker) => {
                let number = marker.number(cst);
                let mark_ident = quote::format_ident!("m{}", number);
                quote! { let #mark_ident = #parser_name.mark(diags); }
            }
            Regex::NodeCreation(creation) => {
                let node_name = creation.node_name(cst).unwrap_or(rule_name);
                let mark = if creation.whole_rule(cst) {
                    quote::format_ident!("start")
                } else {
                    quote::format_ident!("m{}", creation.number(cst).unwrap())
                };
                let variant = snake_to_pascal_case_ident(node_name);
                let create_fn = quote::format_ident!("create_node_{}", node_name);
                quote! {
                    let open_node = #parser_name.open_before(#mark, diags);
                    #parser_name.close(open_node, Rule::#variant, diags);
                    #parser_name.#create_fn(NodeRef(#mark.0), diags);
                }
            }
            Regex::Commit(_) => {
                quote! { #parser_name.in_ordered_choice = false; }
            }
            Regex::Return(_) => {
                let error_handling = match rule_elision {
                    RuleNodeElision::None => {
                        quote! {
                            let closed = #parser_name.close(m, Rule::Error, diags);
                            #parser_name.create_node_error_hook(NodeRef(closed.0), diags);
                        }
                    }
                    RuleNodeElision::Conditional => {
                        quote! {
                            if !elide {
                                let m = #parser_name.open_before(start, diags);
                                let closed = #parser_name.close(m, Rule::Error, diags);
                                #parser_name.create_node_error_hook(NodeRef(closed.0), diags);
                            }
                        }
                    }
                    RuleNodeElision::Unconditional => TokenStream::new(),
                };
                let return_stmt = if in_choice {
                    quote! { return None; }
                } else {
                    quote! { return; }
                };
                quote! {
                    if #parser_name.active_error() {
                        #error_handling
                        #return_stmt
                    }
                }
            }
            Regex::Predicate(_) => TokenStream::new(),
            Regex::Concat(concat) => {
                let ops: Vec<_> = concat
                    .operands(cst)
                    .map(|op| {
                        Self::gen_regex(
                            cst,
                            sema,
                            op,
                            token_symbols,
                            false,
                            rule_name,
                            rule_elision,
                            parser_name,
                            has_rule_rename,
                        )
                    })
                    .collect();
                quote! { #(#ops)* }
            }
            Regex::Paren(paren) => {
                if let Some(inner) = paren.inner(cst) {
                    Self::gen_regex(
                        cst,
                        sema,
                        inner,
                        token_symbols,
                        false,
                        rule_name,
                        rule_elision,
                        parser_name,
                        has_rule_rename,
                    )
                } else {
                    TokenStream::new()
                }
            }
            Regex::Alternation(alt) => {
                let mut arms = Vec::new();
                let mut advance_error_set = BTreeSet::new();
                for op in alt.operands(cst) {
                    let predict = &sema.predict_sets[&op.syntax()];
                    let predicate = Self::gen_predicate(cst, rule_name, op, parser_name);
                    advance_error_set = if predicate.is_none() {
                        advance_error_set.difference(predict).cloned().collect()
                    } else {
                        advance_error_set.union(predict).cloned().collect()
                    };
                    let pattern = gen_pattern(predict);
                    let body = Self::gen_regex(
                        cst,
                        sema,
                        op,
                        token_symbols,
                        false,
                        rule_name,
                        rule_elision,
                        parser_name,
                        has_rule_rename,
                    );
                    let arm = match predicate {
                        Some(pred) => quote! { #pattern if #pred => { #body } },
                        None => quote! { #pattern => { #body } },
                    };
                    arms.push(arm);
                }
                let advance_error_arm = if !advance_error_set.is_empty() {
                    let pattern = gen_pattern(&advance_error_set);
                    let ocr = ordered_choice_return.clone();
                    let msg = gen_syntax_error_message(&[]);
                    quote! {
                        #pattern => {
                            #ocr
                            #parser_name.advance_with_error(diags, err![#parser_name, #msg]);
                        }
                    }
                } else {
                    TokenStream::new()
                };
                let expected =
                    gen_error_message(&sema.predict_sets[&regex.syntax()], token_symbols);
                let ocr = ordered_choice_return;
                quote! {
                    match #parser_name.current {
                        #(#arms)*
                        #advance_error_arm
                        _ => {
                            #ocr
                            #parser_name.error(diags, err![#parser_name, #expected]);
                        }
                    }
                }
            }
            Regex::OrderedChoice(choice) => {
                let ops: Vec<_> = choice.operands(cst).collect();
                let elision_state = if rule_elision == RuleNodeElision::Conditional {
                    quote! { let elision_state = elide; }
                } else {
                    TokenStream::new()
                };
                let elision_restore = if rule_elision == RuleNodeElision::Conditional {
                    quote! { elide = elision_state; }
                } else {
                    TokenStream::new()
                };
                let node_kind_state = if has_rule_rename {
                    quote! { let node_kind_state = node_kind; }
                } else {
                    TokenStream::new()
                };
                let node_kind_restore = if has_rule_rename {
                    quote! { node_kind = node_kind_state; }
                } else {
                    TokenStream::new()
                };
                let mut branches = Vec::new();
                for op in &ops[..ops.len() - 1] {
                    let predict = &sema.predict_sets[&op.syntax()];
                    let predict_pattern = gen_pattern(predict);
                    let body = Self::gen_regex(
                        cst,
                        sema,
                        *op,
                        token_symbols,
                        false,
                        rule_name,
                        rule_elision,
                        parser_name,
                        has_rule_rename,
                    );
                    branches.push(quote! {
                        if matches!(#parser_name.current, #predict_pattern) {
                            if (|| {
                                #body
                                Some(())
                            })().is_some() {
                                break 'ordered_choice;
                            }
                            #parser_name.set_state(&state, diags);
                            #elision_restore
                            #node_kind_restore
                        }
                    });
                }
                let last_op = *ops.last().unwrap();
                let last_predict = &sema.predict_sets[&last_op.syntax()];
                let last_predict_pattern = gen_pattern(last_predict);
                let last_body = Self::gen_regex(
                    cst,
                    sema,
                    last_op,
                    token_symbols,
                    false,
                    rule_name,
                    rule_elision,
                    parser_name,
                    has_rule_rename,
                );
                let invalid_msg = gen_syntax_error_message(&[]);
                quote! {
                    #parser_name.in_ordered_choice = true;
                    'ordered_choice: {
                        let state = #parser_name.get_state(diags);
                        #elision_state
                        #node_kind_state
                        #(#branches)*
                        #parser_name.in_ordered_choice = false;
                        if matches!(#parser_name.current, #last_predict_pattern) {
                            #last_body
                        } else {
                            #parser_name.advance_with_error(diags, err![#parser_name, #invalid_msg]);
                        }
                    }
                }
            }
            Regex::Star(star) => Self::gen_recovering_operation(
                cst,
                sema,
                regex,
                token_symbols,
                open_before,
                rule_name,
                rule_elision,
                parser_name,
                has_rule_rename,
                star.operand(cst).unwrap(),
                ordered_choice_return,
                true,
            ),
            Regex::Plus(plus) => {
                let op = plus.operand(cst).unwrap();
                let op_tokens = Self::gen_regex(
                    cst,
                    sema,
                    op,
                    token_symbols,
                    false,
                    rule_name,
                    rule_elision,
                    parser_name,
                    has_rule_rename,
                );
                let loop_tokens = Self::gen_recovering_operation(
                    cst,
                    sema,
                    regex,
                    token_symbols,
                    open_before,
                    rule_name,
                    rule_elision,
                    parser_name,
                    has_rule_rename,
                    op,
                    ordered_choice_return,
                    true,
                );
                quote! {
                    #op_tokens
                    #loop_tokens
                }
            }
            Regex::Optional(opt) => Self::gen_recovering_operation(
                cst,
                sema,
                regex,
                token_symbols,
                open_before,
                rule_name,
                rule_elision,
                parser_name,
                has_rule_rename,
                opt.operand(cst).unwrap(),
                ordered_choice_return,
                false,
            ),
        }
    }

    fn gen_generated(cst: &Cst<'_>, sema: &SemanticData<'_>, file: File) -> TokenStream {
        let mut token_symbols = FxHashMap::from_iter([("EOF", "<end of file>")]);
        for token in file.token_decls(cst) {
            let name = token.name(cst).unwrap().0;
            let sym = token
                .symbol(cst)
                .map_or(name, |(sym, _)| &sym[1..sym.len() - 1]);
            token_symbols.insert(name, sym);
        }
        let contains_ordered_choice = !sema.used_in_ordered_choice.is_empty();
        let mut rule_names = BTreeMap::from_iter([("error", contains_ordered_choice)]);
        if !sema.parts.is_empty() {
            rule_names.insert("part", false);
        }
        for rule in file.rule_decls(cst) {
            let in_choice = sema.used_in_ordered_choice.contains(&rule.syntax());
            rule_names
                .entry(rule.name(cst).unwrap().0)
                .and_modify(|val| *val |= in_choice)
                .or_insert(in_choice);
        }
        for (rule_name, node_refs) in sema.rule_bindings.iter() {
            let in_choice = node_refs.iter().fold(false, |acc, node_ref| {
                acc | sema.used_in_ordered_choice.contains(node_ref)
            });
            rule_names
                .entry(rule_name)
                .and_modify(|val| *val |= in_choice)
                .or_insert(in_choice);
        }

        // Rule enum: Error must always be first
        let error_variant = snake_to_pascal_case_ident("error");
        let other_rule_variants: Vec<_> = rule_names
            .keys()
            .filter(|n| **n != "error")
            .map(|n| snake_to_pascal_case_ident(n))
            .collect();
        let debug_arms: Vec<_> = rule_names
            .iter()
            .map(|(n, _)| {
                let n = *n;
                let variant = snake_to_pascal_case_ident(n);
                quote! { Rule::#variant => write!(f, #n), }
            })
            .collect();

        // TokenType impl: skip variants with Token:: prefix
        let skip_variants: Vec<_> = {
            let mut v = vec![quote! { Token::Error }];
            for t in &sema.skipped {
                let name = quote::format_ident!("{}", t.name(cst).unwrap().0);
                v.push(quote! { Token::#name });
            }
            v
        };
        // TokenType impl: eof variants with Token:: prefix
        let eof_variants: Vec<_> = {
            let mut v = vec![quote! { Token::EOF }];
            for r in &sema.parts {
                let name = r.name(cst).unwrap().0;
                let eof_name = quote::format_ident!("EOF{}", snake_to_pascal_case(name));
                v.push(quote! { Token::#eof_name });
            }
            v
        };

        // ParserHooks blanket impl
        let create_arms: Vec<_> = rule_names
            .keys()
            .map(|n| {
                let variant = snake_to_pascal_case_ident(*n);
                let create_fn = quote::format_ident!("create_node_{}", n);
                quote! { Rule::#variant => self.#create_fn(node_ref, diags), }
            })
            .collect();
        let delete_arms: Vec<_> = rule_names
            .iter()
            .filter(|(_, in_choice)| **in_choice)
            .map(|(n, _)| {
                let n = *n;
                let variant = snake_to_pascal_case_ident(n);
                let delete_fn = quote::format_ident!("delete_node_{}", n);
                quote! { Rule::#variant => self.#delete_fn(_node_ref), }
            })
            .collect();
        let _delete_covered = rule_names.iter().all(|(_, in_choice)| *in_choice);
        let delete_body = if contains_ordered_choice {
            if _delete_covered {
                quote! { match _rule { #(#delete_arms)* } }
            } else {
                quote! { match _rule { #(#delete_arms)* _ => {} } }
            }
        } else {
            quote! {}
        };

        // Rules trait and impl
        let start_rule = sema.start_rule.unwrap().name(cst).unwrap().0;
        let start_rule_fn = quote::format_ident!("rule_{}", start_rule);
        let start_rule_variant = snake_to_pascal_case_ident(start_rule);
        let parts: Vec<_> = sema
            .parts
            .iter()
            .map(|r| Self::gen_parts_sig(cst, *r))
            .collect();
        let parts_impl: Vec<_> = sema
            .parts
            .iter()
            .map(|r| Self::gen_parts_impl(cst, *r))
            .collect();
        let rule_part_impl = if sema.parts.is_empty() {
            TokenStream::new()
        } else {
            Self::gen_rule_part(cst, sema)
        };
        let rules: Vec<_> = file
            .rule_decls(cst)
            .map(|r| Self::gen_rule(cst, sema, r, &token_symbols))
            .collect();
        let rule_fns: Vec<_> = {
            let mut fns = Vec::new();
            // parse method
            fns.push(quote! {
                fn parse(self, diags: &mut Vec<Self::Diagnostic>) -> Cst<'a, Token, Rule>;
            });
            if !sema.parts.is_empty() {
                let rule_fn = quote::format_ident!("rule_part");
                fns.push(quote! {
                    fn #rule_fn(&mut self, diags: &mut Vec<Self::Diagnostic>);
                });
            }
            for rule in file.rule_decls(cst) {
                if !sema.used.contains(&rule.syntax()) {
                    continue;
                }
                let name = rule.name(cst).unwrap().0;
                let rule_fn = quote::format_ident!("rule_{}", name);
                let in_choice = sema.used_in_ordered_choice.contains(&rule.syntax());
                let ret_type = if in_choice {
                    quote! { -> Option<()> }
                } else {
                    TokenStream::new()
                };
                let attr = if sema.has_rule_rename.contains(&rule) {
                    quote! { #[allow(unused_assignments)] }
                } else {
                    TokenStream::new()
                };
                fns.push(quote! {
                    #attr
                    fn #rule_fn(&mut self, diags: &mut Vec<Self::Diagnostic>) #ret_type;
                });
            }
            fns
        };
        let callbacks = Self::gen_parser_callbacks(sema, true, rule_names);
        let has_left_recursive = sema.recursive.values().any(|branches| {
            branches
                .branches()
                .iter()
                .any(|rec| matches!(rec, Recursion::Left(..) | Recursion::LeftRight(..)))
        });
        let mark_closed_import = if has_left_recursive {
            quote! { , MarkClosed }
        } else {
            TokenStream::new()
        };

        quote! {
                    use lelwel::{TokenType, RuleType, ParserHooks, Parser, NodeRef, Cst, Span, err #mark_closed_import};

                    impl TokenType for Token {
                        #[inline]
                        fn is_skip(&self) -> bool {
                            matches!(self, #(#skip_variants)|*)
                        }
                        #[inline]
                        fn is_eof(&self) -> bool {
                            matches!(self, #(#eof_variants)|*)
                        }
                        #[inline]
                        fn eof() -> Self {
                            Token::EOF
                        }
                    }

                    #[derive(Copy, Clone, PartialEq, Eq)]
                    #[allow(dead_code)]
                    pub enum Rule {
                        #error_variant,
                        #(#other_rule_variants,)*
                    }

                    impl RuleType for Rule {
                        #[inline]
                        fn error() -> Self {
                            Rule::Error
                        }
                    }

                    impl std::fmt::Debug for Rule {
                        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                            match self {
                                #(#debug_arms)*
                            }
                        }
                    }

                    #callbacks

                    impl<'a, Ctx> ParserHooks<'a, Token, Rule> for Parser<'a, Token, Rule, Ctx>
                    where
                        Self: ParserCallbacks<'a>,
                    {
                        type Diag = <Self as ParserCallbacks<'a>>::Diagnostic;
                        type Ctx = <Self as ParserCallbacks<'a>>::Context;

                        #[inline]
                        fn create_tokens_hook(ctx: &mut Self::Ctx, source: &'a str, diags: &mut Vec<Self::Diag>) -> (Vec<Token>, Vec<Span>) {
                            Self::create_tokens(ctx, source, diags)
                        }
                        #[inline]
                        fn create_diagnostic_hook(&self, span: Span, message: String) -> Self::Diag {
                            Self::create_diagnostic(self, span, message)
                        }
                        #[inline]
                        fn predicate_skip_hook(&self, token: Token) -> bool {
                            self.predicate_skip(token)
                        }
                        #[inline]
                        fn create_node(&mut self, rule: Rule, node_ref: NodeRef, diags: &mut Vec<Self::Diag>) {
                            match rule {
                                #(#create_arms)*
                            }
                        }
                        #[inline]
                        fn create_node_error_hook(&mut self, node_ref: NodeRef, diags: &mut Vec<Self::Diag>) {
                            self.create_node_error(node_ref, diags)
                        }
                        #[inline]
                        fn delete_node(&mut self, _rule: Rule, _node_ref: NodeRef) {
                            #delete_body
                        }
                    }

                    macro_rules! expect {
                        ($token:ident, $msg:literal, $self:expr, $diags:expr) => {
                            if let Token::$token = $self.current {
                                $self.advance(false, $diags);
                            } else {
                                $self.error($diags, err![$self, $msg]);
                            }
                        };
                    }
                    #[allow(unused_macros)]
                    macro_rules! try_expect {
                        ($token:ident, $msg:literal, $self:expr, $diags:expr) => {
                            if let Token::$token = $self.current {
                                $self.advance(false, $diags);
                            } else {
                                if $self.in_ordered_choice {
                                    return None;
                                }
                                $self.error($diags, err![$self, $msg]);
                            }
                        };
                    }

        pub trait Rules<'a>: ParserCallbacks<'a> + Sized {
                        #(#parts)*
                        #(#rule_fns)*
                    }

                    #[allow(clippy::while_let_loop, dead_code, unused_parens)]
                    impl<'a, Ctx> Rules<'a> for Parser<'a, Token, Rule, Ctx>
                    where
                        Self: ParserCallbacks<'a>,
                        Ctx: From<<Self as ParserHooks<'a, Token, Rule>>::Ctx>,
                        <Self as ParserHooks<'a, Token, Rule>>::Ctx: From<Ctx>,
                    {
                        fn parse(mut self, diags: &mut Vec<Self::Diagnostic>) -> Cst<'a, Token, Rule> {
                            self.end_of_input = Token::EOF;
                            self.parse_with(|parser, diags| parser.#start_rule_fn(diags), diags, Rule::#start_rule_variant)
                        }
                        #(#parts_impl)*
                        #rule_part_impl
                        #(#rules)*
                    }
                }
    }
}
