// This file was generated by the generate.sh script.
// DO NOT EDIT THIS FILE MANUALLY!

use codespan_reporting::files::SimpleFile;
use codespan_reporting::term::termcolor::NoColor;
use codespan_reporting::term::{self, DisplayStyle};
use lelwel_codegen::frontend::parser::Parser;
use lelwel_codegen::frontend::sema::SemanticPass;
use std::io::BufWriter;

fn gen_diags(input: &str) -> String {
    let source = std::fs::read_to_string(input).unwrap();
    let mut diags = vec![];
    let cst = Parser::new(&source, &mut diags).parse(&mut diags);
    let _ = SemanticPass::run(&cst, &mut diags);

    let mut writer = NoColor::new(BufWriter::new(Vec::new()));
    let config = codespan_reporting::term::Config {
        display_style: DisplayStyle::Short,
        ..Default::default()
    };
    let file = SimpleFile::new(input, &source);
    for diag in diags {
        term::emit_to_write_style(&mut writer, &config, &file, &diag).unwrap();
    }
    std::str::from_utf8(writer.get_ref().buffer())
        .unwrap()
        .to_string()
}

#[test]
#[rustfmt::skip]
fn action_ordered_choice() {
    let diags = gen_diags("tests/frontend/action_ordered_choice.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn calc() {
    let diags = gen_diags("examples/calc/src/calc.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn c() {
    let diags = gen_diags("examples/c/src/c.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn empty() {
    let diags = gen_diags("tests/frontend/empty.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn empty_paren() {
    let diags = gen_diags("tests/frontend/empty_paren.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn invalid_node_create() {
    let diags = gen_diags("tests/frontend/invalid_node_create.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn invalid_token() {
    let diags = gen_diags("tests/frontend/invalid_token.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn json() {
    let diags = gen_diags("examples/json/src/json.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn left_rec_elision() {
    let diags = gen_diags("tests/frontend/left_rec_elision.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn left_rec_node_create() {
    let diags = gen_diags("tests/frontend/left_rec_node_create.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn left_rec_predicate() {
    let diags = gen_diags("tests/frontend/left_rec_predicate.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn left_recursive() {
    let diags = gen_diags("tests/frontend/left_recursive.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn () {
    let diags = gen_diags("");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn ll1_conflict() {
    let diags = gen_diags("tests/frontend/ll1_conflict.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn l() {
    let diags = gen_diags("examples/l/src/l.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn lowercase_token() {
    let diags = gen_diags("tests/frontend/lowercase_token.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn lua() {
    let diags = gen_diags("examples/lua/src/lua.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn mixing_assoc() {
    let diags = gen_diags("tests/frontend/mixing_assoc.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn multiple_start() {
    let diags = gen_diags("tests/frontend/multiple_start.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn node_rename() {
    let diags = gen_diags("tests/frontend/node_rename.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn oberon0() {
    let diags = gen_diags("examples/oberon0/src/oberon0.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn ordered_choice() {
    let diags = gen_diags("tests/frontend/ordered_choice.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn predef_token() {
    let diags = gen_diags("tests/frontend/predef_token.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn predicate_position() {
    let diags = gen_diags("tests/frontend/predicate_position.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn redefinition() {
    let diags = gen_diags("tests/frontend/redefinition.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn redef_node_marker() {
    let diags = gen_diags("tests/frontend/redef_node_marker.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn redef_part() {
    let diags = gen_diags("tests/frontend/redef_part.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn redundant_elision() {
    let diags = gen_diags("tests/frontend/redundant_elision.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn return_start() {
    let diags = gen_diags("tests/frontend/return_start.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn start_as_part() {
    let diags = gen_diags("tests/frontend/start_as_part.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn start_elision() {
    let diags = gen_diags("tests/frontend/start_elision.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn syntax_error() {
    let diags = gen_diags("tests/frontend/syntax_error.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn top_level_ident() {
    let diags = gen_diags("tests/frontend/top_level_ident.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn undefined() {
    let diags = gen_diags("tests/frontend/undefined.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn undef_node_create() {
    let diags = gen_diags("tests/frontend/undef_node_create.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn unused_element() {
    let diags = gen_diags("tests/frontend/unused_element.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn unused_node_marker() {
    let diags = gen_diags("tests/frontend/unused_node_marker.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn unused_part() {
    let diags = gen_diags("tests/frontend/unused_part.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}

#[test]
#[rustfmt::skip]
fn uppercase_rule() {
    let diags = gen_diags("tests/frontend/uppercase_rule.llw");
    let mut lines = diags.lines();

    assert_eq!(lines.next(), Some("error[E0433]: failed to resolve: use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("--> lelwel-codegen/src/bin/llw.rs:27:11"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("27 |     match lelwel::compile("));
    assert_eq!(lines.next(), Some("|           ^^^^^^ use of unresolved module or unlinked crate `lelwel`"));
    assert_eq!(lines.next(), Some("|"));
    assert_eq!(lines.next(), Some("= help: if you wanted to use a crate named `lelwel`, use `cargo add lelwel` to add it to your `Cargo.toml`"));
    assert_eq!(lines.next(), Some("For more information about this error, try `rustc --explain E0433`."));
    assert_eq!(lines.next(), Some("error: could not compile `lelwel-codegen` (bin "llw") due to 1 previous error"));
    assert_eq!(lines.next(), None);
}
