use crate::VERSION;
use crate::frontend::ast::*;
use crate::frontend::parser::{Cst, NodeRef};
use crate::frontend::sema::*;
use proc_macro2::TokenStream;
use quote::quote;
use rustc_hash::{FxHashMap, FxHashSet};
use std::collections::{BTreeMap, BTreeSet};
use std::io::{BufWriter, Write};
use std::path::Path;

pub fn snake_to_pascal_case(name: &str) -> String {
    let mut res = String::new();
    let mut upper = true;
    for c in name.chars() {
        if upper {
            res.push(c.to_ascii_uppercase());
            upper = false;
        } else if c == '_' {
            upper = true;
        } else {
            res.push(c);
        }
    }
    res
}

fn format_rust_source(source: &str) -> String {
    let file = syn::parse_file(source).expect("generated code should be valid Rust");
    prettyplease::unparse(&file)
}

fn gen_pattern(tokens: &BTreeSet<TokenName<'_>>) -> TokenStream {
    let idents: Vec<_> = tokens
        .iter()
        .map(|s| {
            let ident = proc_macro2::Ident::new(&s.0, proc_macro2::Span::call_site());
            quote!(Token::#ident)
        })
        .collect();
    quote!(#(#idents)|*)
}

fn gen_error_message<'a>(
    tokens: &BTreeSet<TokenName<'a>>,
    token_symbols: &FxHashMap<&str, &str>,
) -> TokenStream {
    let expected: Vec<_> = tokens
        .iter()
        .filter_map(|s| token_symbols.get(s.0.as_ref()))
        .map(|sym| {
            if sym.starts_with('<') && sym.ends_with('>') && sym.len() > 2 {
                sym.to_string()
            } else {
                format!("'{}'", sym)
            }
        })
        .collect();
    gen_syntax_error_message(&expected)
}

fn gen_syntax_error_message(expected: &[String]) -> TokenStream {
    let msg = if expected.is_empty() {
        "invalid syntax".to_string()
    } else if expected.len() == 1 {
        format!("invalid syntax, expected: {}", expected[0])
    } else {
        format!("invalid syntax, expected one of: {}", expected.join(", "))
    };
    let unescaped = msg.replace(r"\\", r"\").replace(r"\'", "'");
    quote!(#unescaped)
}

fn self_ident() -> proc_macro2::Ident {
    quote::format_ident!("self")
}

fn parser_ident() -> proc_macro2::Ident {
    quote::format_ident!("parser")
}

fn snake_to_pascal_case_ident(name: &str) -> proc_macro2::Ident {
    quote::format_ident!("{}", snake_to_pascal_case(name))
}

pub struct RustOutput {}

impl RustOutput {
    pub fn run(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        input: &Path,
        output: &Path,
    ) -> std::io::Result<()> {
        let file = File::cast(cst, NodeRef::ROOT).unwrap();
        let generated_tokens = Self::gen_generated(cst, sema, file);
        let generated_source = format!("// generated by lelwel {VERSION}\n\n{generated_tokens}");
        let formatted = format_rust_source(&generated_source);
        let mut generated_file = BufWriter::new(std::fs::File::create(output.join("generated.rs"))?);
        generated_file.write_all(formatted.as_bytes())?;

        let parser_path = input.parent().unwrap().join("parser.rs");
        let lexer_path = input.parent().unwrap().join("lexer.rs");
        if !parser_path.exists() && !lexer_path.exists() {
            let parser_source = Self::gen_parser(sema).to_string();
            let parser_formatted = format_rust_source(&parser_source);
            std::fs::write(&parser_path, parser_formatted)?;

            let lexer_source = Self::gen_lexer(cst, file).to_string();
            let lexer_formatted = format_rust_source(&lexer_source);
            std::fs::write(&lexer_path, lexer_formatted)?;
        }
        Ok(())
    }

    fn gen_parser(sema: &SemanticData<'_>) -> TokenStream {
        let callbacks = Self::gen_parser_callbacks(sema, false, BTreeMap::default());
        quote! {
            use super::lexer::{Token, tokenize};
            use codespan_reporting::diagnostic::Label;
            pub type Diagnostic = codespan_reporting::diagnostic::Diagnostic<()>;
            include!(concat!(env!("OUT_DIR"), "/generated.rs"));
            #callbacks
        }
    }

    fn gen_lexer(cst: &Cst<'_>, file: File) -> TokenStream {
        let mut token_variants = Vec::new();
        token_variants.push(quote! { EOF });
        for token in file.token_decls(cst) {
            if let Some((symbol, _)) = token.symbol(cst)
                && !symbol.is_empty()
                && !(symbol.starts_with("'<") && symbol.ends_with(">'") && symbol.len() > 4)
            {
                let token_str = &symbol[1..symbol.len() - 1];
                let name = proc_macro2::Ident::new(
                    token.name(cst).unwrap().0,
                    proc_macro2::Span::call_site(),
                );
                token_variants.push(quote! { #[token(#token_str)] #name });
                continue;
            }
            let name = proc_macro2::Ident::new(
                token.name(cst).unwrap().0,
                proc_macro2::Span::call_site(),
            );
            token_variants.push(quote! { #name });
        }
        token_variants.push(quote! { Error });
        quote! {
            use super::parser::{Diagnostic, Span};
            use codespan_reporting::diagnostic::Label;
            use logos::Logos;

            #[derive(Debug, Clone, PartialEq, Default)]
            pub enum LexerError {
                #[default]
                Invalid,
            }

            impl LexerError {
                pub fn into_diagnostic(self, span: Span) -> Diagnostic {
                    match self {
                        Self::Invalid => Diagnostic::error()
                            .with_message("invalid token")
                            .with_label(Label::primary((), span)),
                    }
                }
            }

            #[allow(clippy::upper_case_acronyms)]
            #[derive(Logos, Debug, PartialEq, Copy, Clone)]
            #[logos(error = LexerError)]
            pub enum Token {
                #(#token_variants)*
            }

            pub fn tokenize(
                source: &str,
                diags: &mut Vec<Diagnostic>,
            ) -> (Vec<Token>, Vec<Span>) {
                let lexer = Token::lexer(source);
                let mut tokens = vec![];
                let mut spans = vec![];

                for (token, span) in lexer.spanned() {
                    match token {
                        Ok(token) => {
                            tokens.push(token);
                        }
                        Err(err) => {
                            diags.push(err.into_diagnostic(span.clone()));
                            tokens.push(Token::Error);
                        }
                    }
                    spans.push(span);
                }
                (tokens, spans)
            }
        }
    }

    fn gen_parser_callbacks(
        sema: &SemanticData<'_>,
        is_trait: bool,
        rule_names: BTreeMap<&str, bool>,
    ) -> TokenStream {
        if is_trait {
            let mut create_node_methods = Vec::new();
            for rule_name in rule_names.keys() {
                let create_fn = quote::format_ident!("create_node_{}", rule_name);
                let doc = format!("Called when `{rule_name}` node is created.");
                create_node_methods.push(quote! {
                    #[doc = #doc]
                    fn #create_fn(&mut self, _node_ref: NodeRef, _diags: &mut Vec<Self::Diagnostic>) {}
                });
            }

            let mut delete_node_methods = Vec::new();
            for (rule_name, in_choice) in &rule_names {
                if *in_choice {
                    let delete_fn = quote::format_ident!("delete_node_{}", rule_name);
                    let doc = format!("Called when `{rule_name}` node is deleted during backtracking.");
                    delete_node_methods.push(quote! {
                        #[doc = #doc]
                        fn #delete_fn(&mut self, _node_ref: NodeRef) {}
                    });
                }
            }

            let mut predicate_methods = Vec::new();
            let mut seen_predicates = FxHashSet::default();
            for (rule, num) in sema.predicates.values() {
                if seen_predicates.contains(&(rule, num)) {
                    continue;
                }
                seen_predicates.insert((rule, num));
                let pred_fn = quote::format_ident!("predicate_{}_{}", rule, num);
                let doc = format!("Called when semantic predicate `?{num}` in rule `{rule}` is visited.");
                predicate_methods.push(quote! {
                    #[doc = #doc]
                    fn #pred_fn(&self) -> bool;
                });
            }

            let mut action_methods = Vec::new();
            let mut seen_actions = FxHashSet::default();
            for (rule, num) in sema.actions.values() {
                if seen_actions.contains(&(rule, num)) {
                    continue;
                }
                seen_actions.insert((rule, num));
                let action_fn = quote::format_ident!("action_{}_{}", rule, num);
                let doc = format!("Called when semantic action `#{num}` in rule `{rule}` is visited.");
                action_methods.push(quote! {
                    #[doc = #doc]
                    fn #action_fn(&mut self, diags: &mut Vec<Self::Diagnostic>);
                });
            }

            let mut assertion_methods = Vec::new();
            let mut seen_assertions = FxHashSet::default();
            for (rule, num) in sema.assertions.values() {
                if seen_assertions.contains(&(rule, num)) {
                    continue;
                }
                seen_assertions.insert((rule, num));
                let assert_fn = quote::format_ident!("assertion_{}_{}", rule, num);
                let doc = format!("Called when semantic assertion `!{num}` in rule `{rule}` is visited.");
                assertion_methods.push(quote! {
                    #[doc = #doc]
                    fn #assert_fn(&self) -> Option<Self::Diagnostic>;
                });
            }

            let create_tokens_doc = "Called at the start of the parse to generate all tokens and corresponding spans.";
            let create_diagnostic_doc = "Called when diagnostic is created.";
            let predicate_skip_doc = "This predicate can be used to skip normal tokens.";

            quote! {
                #[allow(clippy::ptr_arg)]
                pub trait ParserCallbacks<'a> {
                    type Diagnostic;
                    type Context;

                    #[doc = #create_tokens_doc]
                    fn create_tokens(context: &mut Self::Context, source: &'a str, diags: &mut Vec<Self::Diagnostic>) -> (Vec<Token>, Vec<Span>);
                    #[doc = #create_diagnostic_doc]
                    fn create_diagnostic(&self, span: Span, message: String) -> Self::Diagnostic;
                    #[doc = #predicate_skip_doc]
                    fn predicate_skip(&self, _token: Token) -> bool {
                        false
                    }

                    #(#create_node_methods)*

                    #(#delete_node_methods)*

                    #(#predicate_methods)*

                    #(#action_methods)*

                    #(#assertion_methods)*
                }
            }
        } else {
            let mut predicate_methods = Vec::new();
            let mut seen_predicates = FxHashSet::default();
            for (rule, num) in sema.predicates.values() {
                if seen_predicates.contains(&(rule, num)) {
                    continue;
                }
                seen_predicates.insert((rule, num));
                let pred_fn = quote::format_ident!("predicate_{}_{}", rule, num);
                predicate_methods.push(quote! {
                    fn #pred_fn(&self) -> bool {
                        todo!()
                    }
                });
            }

            let mut action_methods = Vec::new();
            let mut seen_actions = FxHashSet::default();
            for (rule, num) in sema.actions.values() {
                if seen_actions.contains(&(rule, num)) {
                    continue;
                }
                seen_actions.insert((rule, num));
                let action_fn = quote::format_ident!("action_{}_{}", rule, num);
                action_methods.push(quote! {
                    fn #action_fn(&mut self, diags: &mut Vec<Self::Diagnostic>) {
                        todo!()
                    }
                });
            }

            let mut assertion_methods = Vec::new();
            let mut seen_assertions = FxHashSet::default();
            for (rule, num) in sema.assertions.values() {
                if seen_assertions.contains(&(rule, num)) {
                    continue;
                }
                seen_assertions.insert((rule, num));
                let assert_fn = quote::format_ident!("assertion_{}_{}", rule, num);
                assertion_methods.push(quote! {
                    fn #assert_fn(&self) -> Option<Self::Diagnostic> {
                        todo!()
                    }
                });
            }

            quote! {
                impl<'a> ParserCallbacks<'a> for Parser<'a> {
                    type Diagnostic = Diagnostic;
                    type Context = ();

                    fn create_tokens(_context: &mut Self::Context, source: &'a str, diags: &mut Vec<Self::Diagnostic>) -> (Vec<Token>, Vec<Span>) {
                        tokenize(source, diags)
                    }
                    fn create_diagnostic(&self, span: Span, message: String) -> Self::Diagnostic {
                        Self::Diagnostic::error()
                            .with_message(message)
                            .with_label(Label::primary((), span))
                    }

                    #(#predicate_methods)*

                    #(#action_methods)*

                    #(#assertion_methods)*
                }
            }
        }
    }

    fn gen_node_kind_decl(has_rule_rename: bool, name: &str, is_decl: bool) -> TokenStream {
        if !has_rule_rename {
            return TokenStream::new();
        }
        let variant = snake_to_pascal_case_ident(name);
        if is_decl {
            quote! { let mut node_kind = Rule::#variant; }
        } else {
            quote! { node_kind = Rule::#variant; }
        }
    }

    fn gen_cst_close(
        has_rule_rename: bool,
        name: &str,
        assign_lhs: bool,
        parser_name: &proc_macro2::Ident,
        is_start: bool,
    ) -> TokenStream {
        let close_method = if is_start {
            quote::format_ident!("close_root")
        } else {
            quote::format_ident!("close")
        };
        let variant = snake_to_pascal_case_ident(name);
        let close_and_create = if has_rule_rename {
            quote! {
                let closed = #parser_name.#close_method(m, node_kind, diags);
                #parser_name.create_node(node_kind, NodeRef(closed.0), diags);
            }
        } else {
            let create_node_method = quote::format_ident!("create_node_{}", name);
            quote! {
                let closed = #parser_name.#close_method(m, Rule::#variant, diags);
                #parser_name.#create_node_method(NodeRef(closed.0), diags);
            }
        };
        let assign = if assign_lhs {
            quote! { lhs = closed; }
        } else {
            TokenStream::new()
        };
        quote! {
            #close_and_create
            #assign
        }
    }

    fn gen_elision_init(
        has_rule_creation: bool,
        parser_name: &proc_macro2::Ident,
        is_start: bool,
        elision: RuleNodeElision,
    ) -> TokenStream {
        if is_start {
            return TokenStream::new();
        }
        match elision {
            RuleNodeElision::None => quote! {
                let m = #parser_name.open(diags);
            },
            RuleNodeElision::Conditional => quote! {
                let start = #parser_name.mark(diags);
                let mut elide = false;
            },
            RuleNodeElision::Unconditional => {
                if has_rule_creation {
                    quote! { let start = #parser_name.mark(diags); }
                } else {
                    TokenStream::new()
                }
            }
        }
    }

    fn gen_elision_check(
        has_rule_rename: bool,
        name: &str,
        parser_name: &proc_macro2::Ident,
        is_start: bool,
        elision: RuleNodeElision,
    ) -> TokenStream {
        if is_start {
            return TokenStream::new();
        }
        match elision {
            RuleNodeElision::None => {
                Self::gen_cst_close(has_rule_rename, name, false, parser_name, is_start)
            }
            RuleNodeElision::Conditional => {
                let close = Self::gen_cst_close(has_rule_rename, name, false, parser_name, is_start);
                quote! {
                    if !elide {
                        let m = #parser_name.open_before(start, diags);
                        #close
                    }
                }
            }
            RuleNodeElision::Unconditional => TokenStream::new(),
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn gen_normal_rule(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        token_symbols: &FxHashMap<&str, &str>,
        has_rule_rename: bool,
        has_rule_creation: bool,
        name: &str,
        regex: Regex,
        is_start: bool,
        elision: RuleNodeElision,
    ) -> TokenStream {
        let elision_init = Self::gen_elision_init(has_rule_creation, &self_ident(), is_start, elision);
        let node_kind = if !is_start { Self::gen_node_kind_decl(has_rule_rename, name, true) } else { TokenStream::new() };
        let regex_code = Self::gen_regex(cst, sema, regex, token_symbols, false, name, elision, &self_ident(), has_rule_rename);
        let elision_check = Self::gen_elision_check(has_rule_rename, name, &self_ident(), is_start, elision);
        quote! { #elision_init #node_kind #regex_code #elision_check }
    }

    #[allow(clippy::too_many_arguments)]
    fn gen_left_recursive_rule(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        token_symbols: &FxHashMap<&str, &str>,
        has_rule_rename: bool,
        name: &str,
        regex: Regex,
        recursive: &RecursiveBranches,
        in_choice: bool,
    ) -> TokenStream {
        let requires_bp = recursive.branches().len() > 1
            && recursive
                .branches()
                .iter()
                .any(|branch| matches!(branch, Recursion::Right(..) | Recursion::LeftRight(..)));
        let parser = parser_ident();
        let self_ = self_ident();
        let min_bp_param = if requires_bp {
            quote! { min_bp : usize , }
        } else {
            TokenStream::new()
        };
        let ret_type = if in_choice {
            quote! { -> Option < () > }
        } else {
            TokenStream::new()
        };
        let node_kind_decl = Self::gen_node_kind_decl(has_rule_rename, name, true);
        let ops: Vec<Regex> = if let Regex::Alternation(alt) = regex {
            alt.operands(cst).collect()
        } else {
            unreachable!()
        };
        let mut right_arms = Vec::new();
        let mut advance_error_set = BTreeSet::new();
        for alt_op in ops {
            let branch = recursive.get_branch(alt_op);
            if !matches!(branch, None | Some(Recursion::Right(..))) {
                continue;
            }
            let predict = &sema.predict_sets[&alt_op.syntax()];
            let predicate = Self::gen_predicate(cst, name, alt_op, &parser);
            advance_error_set = if predicate.is_none() {
                advance_error_set.difference(predict).cloned().collect()
            } else {
                advance_error_set.union(predict).cloned().collect()
            };
            let predict_pat = gen_pattern(predict);
            let elision = *sema.elision.get(&alt_op.syntax()).unwrap();
            let elision_init = Self::gen_elision_init(false, &parser, false, elision);
            let body = if let Some(Recursion::Right(_, index)) = branch {
                let bp = recursive.binding_power(alt_op).0;
                let Regex::Concat(concat) = alt_op else {
                    unreachable!()
                };
                let mut parts = Vec::new();
                for (i, concat_op) in concat.operands(cst).enumerate() {
                    if i == index {
                        let lhs_ident = quote::format_ident!("lhs");
                        let call = if requires_bp {
                            if in_choice {
                                quote! { rec ( #parser , diags , #bp , #lhs_ident ) ? ; }
                            } else {
                                quote! { rec ( #parser , diags , #bp , #lhs_ident ) ; }
                            }
                        } else if in_choice {
                            quote! { rec ( #parser , diags , #lhs_ident ) ? ; }
                        } else {
                            quote! { rec ( #parser , diags , #lhs_ident ) ; }
                        };
                        parts.push(quote! {
                            let lhs = #parser . mark ( diags ) ;
                            #call
                        });
                    } else {
                        parts.push(Self::gen_regex(
                            cst, sema, concat_op, token_symbols, false, name, elision, &parser, has_rule_rename,
                        ));
                    }
                }
                quote! { # ( #parts ) * }
            } else {
                Self::gen_regex(
                    cst, sema, alt_op, token_symbols, false, name, elision, &parser, has_rule_rename,
                )
            };
            let elision_check = Self::gen_elision_check(has_rule_rename, name, &parser, false, elision);
            let arm = match predicate {
                Some(pred) => quote! {
                    #predict_pat if #pred => {
                        #elision_init
                        #body
                        #elision_check
                    }
                },
                None => quote! {
                    #predict_pat => {
                        #elision_init
                        #body
                        #elision_check
                    }
                },
            };
            right_arms.push(arm);
        }
        let advance_error_arm = if !advance_error_set.is_empty() {
            let pattern = gen_pattern(&advance_error_set);
            let msg = gen_syntax_error_message(&[]);
            quote! {
                #pattern => {
                    #parser . advance_with_error ( diags , err ! [ #parser , #msg ] ) ;
                }
            }
        } else {
            TokenStream::new()
        };
        let expected = gen_error_message(&sema.predict_sets[&regex.syntax()], token_symbols);
        let wildcard_arm = quote! {
            _ => {
                #parser . error ( diags , err ! [ #parser , #expected ] ) ;
            }
        };
        let node_kind_assign = Self::gen_node_kind_decl(has_rule_rename, name, false);
        let mut left_arms = Vec::new();
        for branch in recursive.branches() {
            let (concat, left_index, right_index) = match branch {
                Recursion::Left(Regex::Concat(concat), index) => (concat, *index, None),
                Recursion::LeftRight(Regex::Concat(concat), left_index, right_index) => {
                    (concat, *left_index, Some(*right_index))
                }
                _ => continue,
            };
            let bp = recursive.binding_power(branch.regex());
            let pred = Self::gen_predicate(cst, name, branch.regex(), &parser);
            let mut first_predict = None;
            let mut bp_check = TokenStream::new();
            let mut body_parts = Vec::new();
            let mut is_first = true;
            for (i, concat_op) in concat.operands(cst).enumerate() {
                if let Regex::Predicate(..) = concat_op {
                    continue;
                }
                if i == left_index {
                    continue;
                }
                if is_first {
                    is_first = false;
                    first_predict = Some(gen_pattern(&sema.predict_sets[&concat_op.syntax()]));
                    if requires_bp {
                        let left_bp = bp.0;
                        bp_check = quote! { if #left_bp < min_bp { break ; } }
                    }
                    body_parts.push(quote! { let m = #parser . open_before ( lhs , diags ) ; });
                }
                if right_index == Some(i) {
                    let right_bp = bp.1;
                    let rhs_ident = quote::format_ident!("rhs");
                    let call = if requires_bp {
                        if in_choice {
                            quote! { rec ( #parser , diags , #right_bp , #rhs_ident ) ? ; }
                        } else {
                            quote! { rec ( #parser , diags , #right_bp , #rhs_ident ) ; }
                        }
                    } else if in_choice {
                        quote! { rec ( #parser , diags , #rhs_ident ) ? ; }
                    } else {
                        quote! { rec ( #parser , diags , #rhs_ident ) ; }
                    };
                    body_parts.push(quote! {
                        let rhs = #parser . mark ( diags ) ;
                        #call
                    });
                } else {
                    body_parts.push(Self::gen_regex(
                        cst, sema, concat_op, token_symbols, false, name, RuleNodeElision::None, &parser, has_rule_rename,
                    ));
                }
            }
            let close = Self::gen_cst_close(has_rule_rename, name, true, &parser, false);
            let predict_pat = first_predict.unwrap();
            let arm = match pred {
                Some(p) => quote! {
                    #predict_pat if #p => {
                        #bp_check
                        # ( #body_parts ) *
                        #close
                        continue ;
                    }
                },
                None => quote! {
                    #predict_pat => {
                        #bp_check
                        # ( #body_parts ) *
                        #close
                        continue ;
                    }
                },
            };
            left_arms.push(arm);
        }
        let some_return = if in_choice {
            quote! { Some ( () ) }
        } else {
            TokenStream::new()
        };
        let lhs_ident = quote::format_ident!("lhs");
        let outer_call = if requires_bp {
            if in_choice {
                quote! { rec ( #self_ , diags , 0 , #lhs_ident ) ? ; }
            } else {
                quote! { rec ( #self_ , diags , 0 , #lhs_ident ) ; }
            }
        } else if in_choice {
            quote! { rec ( #self_ , diags , #lhs_ident ) ? ; }
        } else {
            quote! { rec ( #self_ , diags , #lhs_ident ) ; }
        };
        quote! {
            fn rec < 'a > (
                parser : & mut Parser < 'a > ,
                diags : & mut Vec < < Parser < 'a > as ParserCallbacks < 'a > > :: Diagnostic > ,
                #min_bp_param
                mut lhs : MarkClosed ,
            ) #ret_type {
                #node_kind_decl
                match #parser . current {
                    # ( #right_arms ) *
                    #advance_error_arm
                    #wildcard_arm
                }
                loop {
                    #node_kind_assign
                    match #parser . current {
                        # ( #left_arms ) *
                        _ => {
                            break ;
                        }
                    }
                }
                #some_return
            }
            let #lhs_ident = #self_ . mark ( diags ) ;
            #outer_call
        }
    }

    fn gen_parts(cst: &Cst<'_>, rule: RuleDecl) -> TokenStream {
        let name = rule.name(cst).unwrap().0;
        let parse_fn = quote::format_ident!("parse_{}", name);
        let rule_fn = quote::format_ident!("rule_{}", name);
        let eof_variant = quote::format_ident!("EOF{}", snake_to_pascal_case(name));
        let doc = format!("Returns the CST for a parse of the {name} rule");
        quote! {
            #[doc = #doc]
            pub fn #parse_fn(mut self, diags: &mut Vec<Diagnostic>) -> Cst<'a> {
                self.end_of_input = Token::#eof_variant;
                self.parse_rule(|parser, diags| parser.#rule_fn(diags), diags, Rule::Part)
            }
        }
    }

    fn gen_rule(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        rule: RuleDecl,
        token_symbols: &FxHashMap<&str, &str>,
    ) -> TokenStream {
        if !sema.used.contains(&rule.syntax()) {
            return TokenStream::new();
        }
        let name = rule.name(cst).unwrap().0;
        let recursive = sema.recursive.get(&rule);
        let is_start = sema.start_rule.unwrap() == rule;
        let has_rule_rename = sema.has_rule_rename.contains(&rule);
        let has_rule_creation = sema.has_rule_creation.contains(&rule);
        let elision = if rule.is_elided(cst) {
            RuleNodeElision::Unconditional
        } else {
            rule.regex(cst)
                .and_then(|regex| sema.elision.get(&regex.syntax()))
                .copied()
                .unwrap_or(RuleNodeElision::None)
        };
        let in_choice = sema.used_in_ordered_choice.contains(&rule.syntax());
        let rule_fn = quote::format_ident!("rule_{}", name);
        let attr = if has_rule_rename {
            quote! { # [ allow ( unused_assignments ) ] }
        } else {
            TokenStream::new()
        };
        let ret_type = if in_choice {
            quote! { -> Option < () > }
        } else {
            TokenStream::new()
        };
        let body = if let Some(regex) = rule.regex(cst) {
            if recursive.is_some_and(|recursive| {
                recursive
                    .branches()
                    .iter()
                    .any(|rec| matches!(rec, Recursion::Left(..) | Recursion::LeftRight(..)))
            }) {
                Self::gen_left_recursive_rule(
                    cst, sema, token_symbols, has_rule_rename, name, regex, recursive.unwrap(), in_choice,
                )
            } else {
                Self::gen_normal_rule(
                    cst, sema, token_symbols, has_rule_rename, has_rule_creation, name, regex, is_start, elision,
                )
            }
        } else {
            TokenStream::new()
        };
        let return_val = if in_choice {
            quote! { Some ( () ) }
        } else {
            TokenStream::new()
        };
        quote! {
            #attr
            fn #rule_fn ( & mut self , diags : & mut Vec < < Self as ParserCallbacks < 'a > > :: Diagnostic > ) #ret_type {
                #body
                #return_val
            }
        }
    }

    fn gen_predicate(cst: &Cst<'_>, rule_name: &str, regex: Regex, parser_name: &proc_macro2::Ident) -> Option<TokenStream> {
        match regex {
            Regex::Concat(concat) => match concat.operands(cst).next().unwrap() {
                Regex::Predicate(pred) => {
                    if pred.is_true(cst) {
                        Some(quote! { true })
                    } else {
                        let num = &pred.value(cst).unwrap().0[1..];
                        let method = quote::format_ident!("predicate_{}_{}", rule_name, num);
                        Some(quote! { #parser_name.#method() })
                    }
                }
                _ => None,
            },
            Regex::Paren(paren) => {
                if let Some(inner) = paren.inner(cst) {
                    Self::gen_predicate(cst, rule_name, inner, parser_name)
                } else {
                    None
                }
            }
            _ => None,
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn gen_recovering_operation(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        regex: Regex,
        token_symbols: &FxHashMap<&str, &str>,
        open_before: bool,
        rule_name: &str,
        rule_elision: RuleNodeElision,
        parser_name: &proc_macro2::Ident,
        has_rule_rename: bool,
        op: Regex,
        ordered_choice_return: TokenStream,
        is_loop: bool,
    ) -> TokenStream {
        let first_pattern = gen_pattern(&sema.first_sets[&op.syntax()]);
        let predicate = Self::gen_predicate(cst, rule_name, op, parser_name);
        let open_before_block = if open_before {
            quote! {
                if m.is_none() {
                    m = Some(#parser_name.open_before(lhs, diags));
                }
            }
        } else {
            TokenStream::new()
        };
        let body = Self::gen_regex(
            cst, sema, op, token_symbols, false, rule_name, rule_elision, parser_name, has_rule_rename,
        );
        let break_if_not_loop = if !is_loop {
            quote! { break; }
        } else {
            TokenStream::new()
        };
        let follow_pattern = gen_pattern(&sema.follow_sets[&regex.syntax()]);
        let expected = if is_loop {
            gen_error_message(&sema.follow_sets[&op.syntax()], token_symbols)
        } else {
            gen_error_message(&sema.predict_sets[&regex.syntax()], token_symbols)
        };
        let recovery = &sema.recovery_sets[&regex.syntax()];
        let recovery_arm = if recovery.is_empty() {
            TokenStream::new()
        } else {
            let recovery_pattern = gen_pattern(recovery);
            let ocr = ordered_choice_return.clone();
            quote! {
                | #recovery_pattern => {
                    #ocr
                    #parser_name.error(diags, err![#parser_name, #expected]);
                    break;
                }
            }
        };
        let ocr = ordered_choice_return;
        let first_arm = match predicate {
            Some(pred) => quote! { #first_pattern if #pred => { #open_before_block #body #break_if_not_loop } },
            None => quote! { #first_pattern => { #open_before_block #body #break_if_not_loop } },
        };
        quote! {
            loop {
                match #parser_name.current {
                    #first_arm
                    #follow_pattern => break,
                    #recovery_arm
                    _ => {
                        #ocr
                        #parser_name.advance_with_error(diags, err![#parser_name, #expected]);
                    }
                }
            }
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn gen_regex(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        regex: Regex,
        token_symbols: &FxHashMap<&str, &str>,
        open_before: bool,
        rule_name: &str,
        rule_elision: RuleNodeElision,
        parser_name: &proc_macro2::Ident,
        has_rule_rename: bool,
    ) -> TokenStream {
        let in_choice = sema.used_in_ordered_choice.contains(&regex.syntax());
        let expect_macro = if in_choice {
            quote::format_ident!("try_expect")
        } else {
            quote::format_ident!("expect")
        };
        let ordered_choice_return = if in_choice {
            quote! {
                if #parser_name.in_ordered_choice {
                    return None;
                }
            }
        } else {
            TokenStream::new()
        };
        match regex {
            Regex::Name(name) => {
                let decl = sema.decl_bindings[&name.syntax()];
                if let Some(rule) = RuleDecl::cast(cst, decl) {
                    let name = rule.name(cst).unwrap().0;
                    let rule_in_choice = sema.used_in_ordered_choice.contains(&rule.syntax());
                    let rule_fn = quote::format_ident!("rule_{}", name);
                    if rule_in_choice && in_choice {
                        quote! { #parser_name.#rule_fn(diags)?; }
                    } else {
                        quote! { #parser_name.#rule_fn(diags); }
                    }
                } else if let Some(token) = TokenDecl::cast(cst, decl) {
                    let name = token.name(cst).unwrap().0;
                    let sym = token
                        .symbol(cst)
                        .map_or(name, |(sym, _)| &sym[1..sym.len() - 1]);
                    let token_ident = quote::format_ident!("{}", name);
                    let error_msg = gen_syntax_error_message(&[sym.to_string()]);
                    quote! { #expect_macro!(#token_ident, #error_msg, #parser_name, diags); }
                } else {
                    TokenStream::new()
                }
            }
            Regex::Symbol(sym) => {
                let decl = sema.decl_bindings[&sym.syntax()];
                if let Some(token) = TokenDecl::cast(cst, decl) {
                    let name = token.name(cst).unwrap().0;
                    let sym_val = token.symbol(cst).unwrap().0;
                    let token_ident = quote::format_ident!("{}", name);
                    let error_msg = gen_syntax_error_message(&[sym_val.to_string()]);
                    quote! { #expect_macro!(#token_ident, #error_msg, #parser_name, diags); }
                } else {
                    TokenStream::new()
                }
            }
            Regex::Action(action) => {
                let num = &action.value(cst).unwrap().0[1..];
                let method = quote::format_ident!("action_{}_{}", rule_name, num);
                quote! { #parser_name.#method(diags); }
            }
            Regex::Assertion(assertion) => {
                let num = &assertion.value(cst).unwrap().0[1..];
                let method = quote::format_ident!("assertion_{}_{}", rule_name, num);
                let ocr = ordered_choice_return.clone();
                quote! {
                    if let Some(diag) = #parser_name.#method() {
                        #ocr
                        #parser_name.error_since_advance = true;
                        diags.push(diag);
                    }
                }
            }
            Regex::NodeRename(rename) => {
                let name = &rename.value(cst).unwrap().0[1..];
                if !name.is_empty() {
                    let variant = snake_to_pascal_case_ident(name);
                    quote! { node_kind = Rule::#variant; }
                } else {
                    TokenStream::new()
                }
            }
            Regex::NodeElision(_) => {
                if rule_elision == RuleNodeElision::Conditional {
                    quote! { elide = true; }
                } else {
                    TokenStream::new()
                }
            }
            Regex::NodeMarker(marker) => {
                let number = marker.number(cst);
                let mark_ident = quote::format_ident!("m{}", number);
                quote! { let #mark_ident = #parser_name.mark(diags); }
            }
            Regex::NodeCreation(creation) => {
                let node_name = creation.node_name(cst).unwrap_or(rule_name);
                let mark = if creation.whole_rule(cst) {
                    quote::format_ident!("start")
                } else {
                    quote::format_ident!("m{}", creation.number(cst).unwrap())
                };
                let variant = snake_to_pascal_case_ident(node_name);
                let create_fn = quote::format_ident!("create_node_{}", node_name);
                quote! {
                    let open_node = #parser_name.open_before(#mark, diags);
                    #parser_name.close(open_node, Rule::#variant, diags);
                    #parser_name.#create_fn(NodeRef(#mark.0), diags);
                }
            }
            Regex::Commit(_) => {
                quote! { #parser_name.in_ordered_choice = false; }
            }
            Regex::Return(_) => {
                let error_handling = match rule_elision {
                    RuleNodeElision::None => {
                        quote! {
                            let closed = #parser_name.close(m, Rule::Error, diags);
                            #parser_name.create_node_error(NodeRef(closed.0), diags);
                        }
                    }
                    RuleNodeElision::Conditional => {
                        quote! {
                            if !elide {
                                let m = #parser_name.open_before(start, diags);
                                let closed = #parser_name.close(m, Rule::Error, diags);
                                #parser_name.create_node_error(NodeRef(closed.0), diags);
                            }
                        }
                    }
                    RuleNodeElision::Unconditional => TokenStream::new(),
                };
                let return_stmt = if in_choice {
                    quote! { return None; }
                } else {
                    quote! { return; }
                };
                quote! {
                    if #parser_name.active_error() {
                        #error_handling
                        #return_stmt
                    }
                }
            }
            Regex::Predicate(_) => TokenStream::new(),
            Regex::Concat(concat) => {
                let ops: Vec<_> = concat
                    .operands(cst)
                    .map(|op| {
                        Self::gen_regex(
                            cst, sema, op, token_symbols, false, rule_name, rule_elision, parser_name, has_rule_rename,
                        )
                    })
                    .collect();
                quote! { #(#ops)* }
            }
            Regex::Paren(paren) => {
                if let Some(inner) = paren.inner(cst) {
                    Self::gen_regex(
                        cst, sema, inner, token_symbols, false, rule_name, rule_elision, parser_name, has_rule_rename,
                    )
                } else {
                    TokenStream::new()
                }
            }
            Regex::Alternation(alt) => {
                let mut arms = Vec::new();
                let mut advance_error_set = BTreeSet::new();
                for op in alt.operands(cst) {
                    let predict = &sema.predict_sets[&op.syntax()];
                    let predicate = Self::gen_predicate(cst, rule_name, op, parser_name);
                    advance_error_set = if predicate.is_none() {
                        advance_error_set.difference(predict).cloned().collect()
                    } else {
                        advance_error_set.union(predict).cloned().collect()
                    };
                    let pattern = gen_pattern(predict);
                    let body = Self::gen_regex(
                        cst, sema, op, token_symbols, false, rule_name, rule_elision, parser_name, has_rule_rename,
                    );
                    let arm = match predicate {
                        Some(pred) => quote! { #pattern if #pred => { #body } },
                        None => quote! { #pattern => { #body } },
                    };
                    arms.push(arm);
                }
                let advance_error_arm = if !advance_error_set.is_empty() {
                    let pattern = gen_pattern(&advance_error_set);
                    let ocr = ordered_choice_return.clone();
                    let msg = gen_syntax_error_message(&[]);
                    quote! {
                        #pattern => {
                            #ocr
                            #parser_name.advance_with_error(diags, err![#parser_name, #msg]);
                        }
                    }
                } else {
                    TokenStream::new()
                };
                let expected = gen_error_message(&sema.predict_sets[&regex.syntax()], token_symbols);
                let ocr = ordered_choice_return;
                quote! {
                    match #parser_name.current {
                        #(#arms)*
                        #advance_error_arm
                        _ => {
                            #ocr
                            #parser_name.error(diags, err![#parser_name, #expected]);
                        }
                    }
                }
            }
            Regex::OrderedChoice(choice) => {
                let ops: Vec<_> = choice.operands(cst).collect();
                let elision_state = if rule_elision == RuleNodeElision::Conditional {
                    quote! { let elision_state = elide; }
                } else {
                    TokenStream::new()
                };
                let elision_restore = if rule_elision == RuleNodeElision::Conditional {
                    quote! { elide = elision_state; }
                } else {
                    TokenStream::new()
                };
                let node_kind_state = if has_rule_rename {
                    quote! { let node_kind_state = node_kind; }
                } else {
                    TokenStream::new()
                };
                let node_kind_restore = if has_rule_rename {
                    quote! { node_kind = node_kind_state; }
                } else {
                    TokenStream::new()
                };
                let mut branches = Vec::new();
                for op in &ops[..ops.len() - 1] {
                    let predict = &sema.predict_sets[&op.syntax()];
                    let predict_pattern = gen_pattern(predict);
                    let body = Self::gen_regex(
                        cst, sema, *op, token_symbols, false, rule_name, rule_elision, parser_name, has_rule_rename,
                    );
                    branches.push(quote! {
                        if matches!(#parser_name.current, #predict_pattern) {
                            if (|| {
                                #body
                                Some(())
                            })().is_some() {
                                break 'ordered_choice;
                            }
                            #parser_name.set_state(&state, diags);
                            #elision_restore
                            #node_kind_restore
                        }
                    });
                }
                let last_op = *ops.last().unwrap();
                let last_predict = &sema.predict_sets[&last_op.syntax()];
                let last_predict_pattern = gen_pattern(last_predict);
                let last_body = Self::gen_regex(
                    cst, sema, last_op, token_symbols, false, rule_name, rule_elision, parser_name, has_rule_rename,
                );
                let invalid_msg = gen_syntax_error_message(&[]);
                quote! {
                    #parser_name.in_ordered_choice = true;
                    'ordered_choice: {
                        let state = #parser_name.get_state(diags);
                        #elision_state
                        #node_kind_state
                        #(#branches)*
                        #parser_name.in_ordered_choice = false;
                        if matches!(#parser_name.current, #last_predict_pattern) {
                            #last_body
                        } else {
                            #parser_name.advance_with_error(diags, err![#parser_name, #invalid_msg]);
                        }
                    }
                }
            }
            Regex::Star(star) => {
                Self::gen_recovering_operation(
                    cst, sema, regex, token_symbols, open_before,
                    rule_name, rule_elision, parser_name, has_rule_rename,
                    star.operand(cst).unwrap(), ordered_choice_return, true,
                )
            }
            Regex::Plus(plus) => {
                let op = plus.operand(cst).unwrap();
                let op_tokens = Self::gen_regex(
                    cst, sema, op, token_symbols, false, rule_name, rule_elision, parser_name, has_rule_rename,
                );
                let loop_tokens = Self::gen_recovering_operation(
                    cst, sema, regex, token_symbols, open_before,
                    rule_name, rule_elision, parser_name, has_rule_rename,
                    op, ordered_choice_return, true,
                );
                quote! {
                    #op_tokens
                    #loop_tokens
                }
            }
            Regex::Optional(opt) => {
                Self::gen_recovering_operation(
                    cst, sema, regex, token_symbols, open_before,
                    rule_name, rule_elision, parser_name, has_rule_rename,
                    opt.operand(cst).unwrap(), ordered_choice_return, false,
                )
            }
        }
    }

    fn gen_generated(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        file: File,
    ) -> TokenStream {
        let mut token_symbols = FxHashMap::from_iter([("EOF", "<end of file>")]);
        for token in file.token_decls(cst) {
            let name = token.name(cst).unwrap().0;
            let sym = token
                .symbol(cst)
                .map_or(name, |(sym, _)| &sym[1..sym.len() - 1]);
            token_symbols.insert(name, sym);
        }
        let contains_ordered_choice = !sema.used_in_ordered_choice.is_empty();
        let mut rule_names = BTreeMap::from_iter([("error", contains_ordered_choice)]);
        if !sema.parts.is_empty() {
            rule_names.insert("part", false);
        }
        for rule in file.rule_decls(cst) {
            let in_choice = sema.used_in_ordered_choice.contains(&rule.syntax());
            rule_names
                .entry(rule.name(cst).unwrap().0)
                .and_modify(|val| *val |= in_choice)
                .or_insert(in_choice);
        }
        for (rule_name, node_refs) in sema.rule_bindings.iter() {
            let in_choice = node_refs.iter().fold(false, |acc, node_ref| {
                acc | sema.used_in_ordered_choice.contains(node_ref)
            });
            rule_names
                .entry(rule_name)
                .and_modify(|val| *val |= in_choice)
                .or_insert(in_choice);
        }
        let rule_variants: Vec<_> = rule_names
            .keys()
            .map(|n| snake_to_pascal_case_ident(n))
            .collect();
        let debug_arms: Vec<_> = rule_names
            .iter()
            .map(|(n, _)| {
                let n = *n;
                let variant = snake_to_pascal_case_ident(n);
                quote! { Rule::#variant => write!(f, #n), }
            })
            .collect();
        let skip_idents: Vec<_> = sema
            .skipped
            .iter()
            .map(|t| {
                let name = quote::format_ident!("{}", t.name(cst).unwrap().0);
                quote! { | Token::#name }
            })
            .collect();
        let create_arms: Vec<_> = rule_names
            .keys()
            .map(|n| {
                let variant = snake_to_pascal_case_ident(*n);
                let create_fn = quote::format_ident!("create_node_{}", n);
                quote! { Rule::#variant => self.#create_fn(node_ref, diags), }
            })
            .collect();
        let delete_arms: Vec<_> = rule_names
            .iter()
            .filter(|(_, in_choice)| **in_choice)
            .map(|(n, _)| {
                let n = *n;
                let variant = snake_to_pascal_case_ident(n);
                let delete_fn = quote::format_ident!("delete_node_{}", n);
                quote! { Rule::#variant => self.#delete_fn(_node_ref), }
            })
            .collect();
        let delete_covered = rule_names.iter().all(|(_, in_choice)| *in_choice);
        let delete_body = if contains_ordered_choice {
            if delete_covered {
                quote! { match _rule { #(#delete_arms)* } }
            } else {
                quote! { match _rule { #(#delete_arms)* _ => {} } }
            }
        } else {
            quote! {}
        };
        let start_rule = sema.start_rule.unwrap().name(cst).unwrap().0;
        let start_rule_fn = quote::format_ident!("rule_{}", start_rule);
        let start_rule_variant = snake_to_pascal_case_ident(start_rule);
        let parts: Vec<_> = sema
            .parts
            .iter()
            .map(|r| Self::gen_parts(cst, *r))
            .collect();
        let rules: Vec<_> = file
            .rule_decls(cst)
            .map(|r| Self::gen_rule(cst, sema, r, &token_symbols))
            .collect();
        let callbacks = Self::gen_parser_callbacks(sema, true, rule_names);

        quote! {
            macro_rules! err {
                [$self:expr, $msg:literal] => {
                    $self.create_diagnostic($self.span(), String::from($msg))
                }
            }

            #[derive(Copy, Clone, PartialEq, Eq)]
            #[allow(dead_code)]
            pub enum Rule {
                #(#rule_variants,)*
            }

            #[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, Ord, PartialOrd)]
            pub struct NodeRef(pub usize);

            impl NodeRef {
                #[allow(dead_code)]
                pub const ROOT: NodeRef = NodeRef(0);
            }

            #[cfg(target_pointer_width = "64")]
            #[derive(Copy, Clone)]
            pub struct CstIndex([u8; 6]);

            #[cfg(any(target_pointer_width = "16", target_pointer_width = "32"))]
            #[derive(Copy, Clone)]
            pub struct CstIndex(usize);

            impl std::fmt::Debug for CstIndex {
                fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
                    usize::from(*self).fmt(f)
                }
            }

            impl From<CstIndex> for usize {
                #[cfg(target_pointer_width = "64")]
                #[inline]
                fn from(value: CstIndex) -> Self {
                    let [b0, b1, b2, b3, b4, b5] = value.0;
                    usize::from_le_bytes([b0, b1, b2, b3, b4, b5, 0, 0])
                }
                #[cfg(any(target_pointer_width = "16", target_pointer_width = "32"))]
                #[inline]
                fn from(value: CstIndex) -> Self {
                    value.0
                }
            }
            impl From<usize> for CstIndex {
                #[cfg(target_pointer_width = "64")]
                #[inline]
                fn from(value: usize) -> Self {
                    let [b0, b1, b2, b3, b4, b5, b6, b7] = value.to_le_bytes();
                    debug_assert!(b6 == 0 && b7 == 0);
                    Self([b0, b1, b2, b3, b4, b5])
                }
                #[cfg(any(target_pointer_width = "16", target_pointer_width = "32"))]
                #[inline]
                fn from(value: usize) -> Self {
                    Self(value)
                }
            }

            #[derive(Debug, Copy, Clone)]
            pub enum Node {
                Rule(Rule, CstIndex),
                Token(Token, CstIndex),
            }

            #[derive(Clone, Copy)]
            struct MarkOpened(usize);
            #[derive(Clone, Copy)]
            struct MarkClosed(usize);
            #[derive(Clone)]
            struct MarkTruncation {
                node_count: usize,
                token_count: usize,
                non_skip_len: usize,
            }

            #[derive(Default)]
            pub struct CstChildren<'a> {
                iter: std::slice::Iter<'a, Node>,
                offset: usize,
            }
            impl Iterator for CstChildren<'_> {
                type Item = NodeRef;

                fn next(&mut self) -> Option<Self::Item> {
                    let offset = self.offset;
                    self.offset += 1;
                    if let Some(node) = self.iter.next() {
                        if let Node::Rule(_, end_offset) = node {
                            let end_offset = usize::from(*end_offset);
                            if end_offset > 0 {
                                self.iter.nth(end_offset.saturating_sub(1));
                                self.offset += end_offset;
                            }
                        }
                        Some(NodeRef(offset))
                    } else {
                        None
                    }
                }
            }

            pub type Span = core::ops::Range<usize>;

            #[derive(Debug)]
            pub struct CstData {
                spans: Vec<Span>,
                nodes: Vec<Node>,
                token_count: usize,
                non_skip_len: usize,
            }
            #[allow(dead_code)]
            impl CstData {
                fn new(spans: Vec<Span>) -> Self {
                    let nodes = Vec::with_capacity(spans.len() * 2);
                    Self {
                        spans,
                        nodes,
                        token_count: 0,
                        non_skip_len: 0,
                    }
                }
                fn open(&mut self) -> MarkOpened {
                    let mark = MarkOpened(self.nodes.len());
                    self.nodes.push(Node::Rule(Rule::Error, 0.into()));
                    self.non_skip_len = self.nodes.len();
                    mark
                }
                fn close(&mut self, mark: MarkOpened, rule: Rule) -> MarkClosed {
                    let len = self.non_skip_len - 1;
                    self.nodes[mark.0] = Node::Rule(
                        rule,
                        if mark.0 > len {
                            self.non_skip_len += mark.0 - len;
                            0
                        } else {
                            len - mark.0
                        }
                        .into(),
                    );
                    MarkClosed(mark.0)
                }
                fn close_root(&mut self, mark: MarkOpened, rule: Rule) -> MarkClosed {
                    self.nodes[mark.0] = Node::Rule(rule, (self.nodes.len() - 1 - mark.0).into());
                    MarkClosed(mark.0)
                }
                fn advance(&mut self, token: Token, skip: bool) {
                    self.nodes.push(Node::Token(token, self.token_count.into()));
                    self.token_count += 1;
                    if !skip {
                        self.non_skip_len = self.nodes.len();
                    }
                }
                fn open_before(&mut self, mark: MarkClosed) -> MarkOpened {
                    self.nodes.insert(mark.0, Node::Rule(Rule::Error, 0.into()));
                    self.non_skip_len += 1;
                    MarkOpened(mark.0)
                }
                fn mark(&self) -> MarkClosed {
                    MarkClosed(self.nodes.len())
                }
                fn mark_truncation(&self) -> MarkTruncation {
                    MarkTruncation {
                        node_count: self.nodes.len(),
                        token_count: self.token_count,
                        non_skip_len: self.non_skip_len,
                    }
                }
                fn truncate(&mut self, mark: MarkTruncation) {
                    self.nodes.truncate(mark.node_count);
                    self.token_count = mark.token_count;
                    self.non_skip_len = mark.non_skip_len;
                }
                pub fn children(&self, node_ref: NodeRef) -> CstChildren<'_> {
                    let iter = if let Node::Rule(_, end_offset) = self.nodes[node_ref.0] {
                        self.nodes[node_ref.0 + 1..node_ref.0 + usize::from(end_offset) + 1].iter()
                    } else {
                        std::slice::Iter::default()
                    };
                    CstChildren {
                        iter,
                        offset: node_ref.0 + 1,
                    }
                }
                pub fn get(&self, node_ref: NodeRef) -> Node {
                    self.nodes[node_ref.0]
                }
                pub fn span(&self, node_ref: NodeRef) -> Span {
                    fn find_token<'a>(mut iter: impl Iterator<Item = &'a Node>) -> Option<usize> {
                        iter.find_map(|node| match node {
                            Node::Rule(..) => None,
                            Node::Token(_, idx) => Some(usize::from(*idx)),
                        })
                    }
                    match self.nodes[node_ref.0] {
                        Node::Token(_, idx) => self.spans[usize::from(idx)].clone(),
                        Node::Rule(_, end_offset) => {
                            let end = node_ref.0 + usize::from(end_offset);
                            let first = find_token(self.nodes[node_ref.0 + 1..=end].iter());
                            let last = find_token(self.nodes[node_ref.0 + 1..=end].iter().rev());
                            if let (Some(first), Some(last)) = (first, last) {
                                self.spans[first].start..self.spans[last].end
                            } else {
                                let offset = find_token(self.nodes[..node_ref.0].iter().rev())
                                    .map_or(0, |before| self.spans[before].end);
                                offset..offset
                            }
                        }
                    }
                }
                pub fn match_token(&self, node_ref: NodeRef, matched_token: Token) -> Option<Span> {
                    match self.nodes[node_ref.0] {
                        Node::Token(token, idx) if token == matched_token => {
                            Some(self.spans[usize::from(idx)].clone())
                        }
                        _ => None,
                    }
                }
                pub fn match_rule(&self, node_ref: NodeRef, matched_rule: Rule) -> bool {
                    matches!(self.nodes[node_ref.0], Node::Rule(rule, _) if rule == matched_rule)
                }
            }

            #[derive(Debug)]
            pub struct Cst<'a> {
                source: &'a str,
                data: CstData,
            }
            #[allow(dead_code)]
            impl<'a> Cst<'a> {
                pub fn source(&self) -> &'a str {
                    self.source
                }
                pub fn into_data(self) -> CstData {
                    self.data
                }
                pub fn children(&self, node_ref: NodeRef) -> CstChildren<'_> {
                    self.data.children(node_ref)
                }
                pub fn get(&self, node_ref: NodeRef) -> Node {
                    self.data.get(node_ref)
                }
                pub fn span(&self, node_ref: NodeRef) -> Span {
                    self.data.span(node_ref)
                }
                pub fn match_token(&self, node_ref: NodeRef, matched_token: Token) -> Option<(&'a str, Span)> {
                    self.data.match_token(node_ref, matched_token).map(|span| (&self.source[span.clone()], span))
                }
                pub fn match_rule(&self, node_ref: NodeRef, matched_rule: Rule) -> bool {
                    self.data.match_rule(node_ref, matched_rule)
                }
                pub fn span_text(&self, span_idx: CstIndex) -> &'a str {
                    &self.source[self.data.spans[usize::from(span_idx)].clone()]
                }
            }

            impl std::fmt::Display for Cst<'_> {
                fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                    const DEPTH: &str = "    ";
                    fn rec(
                        cst: &Cst<'_>,
                        f: &mut std::fmt::Formatter<'_>,
                        node_ref: NodeRef,
                        indent: usize,
                    ) -> std::fmt::Result {
                        match cst.get(node_ref) {
                            Node::Rule(rule, _) => {
                                let span = cst.span(node_ref);
                                writeln!(f, "{}{rule:?} [{span:?}]", DEPTH.repeat(indent))?;
                                for child_node_ref in cst.children(node_ref) {
                                    rec(cst, f, child_node_ref, indent + 1)?;
                                }
                                Ok(())
                            }
                            Node::Token(token, idx) => {
                                let span = &cst.data.spans[usize::from(idx)];
                                writeln!(
                                    f,
                                    "{}{:?} {:?} [{:?}]",
                                    DEPTH.repeat(indent),
                                    token,
                                    &cst.source[span.clone()],
                                    span,
                                )
                            }
                        }
                    }
                    rec(self, f, NodeRef::ROOT, 0)
                }
            }

            impl std::fmt::Debug for Rule {
                fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                    match self {
                        #(#debug_arms)*
                    }
                }
            }

            macro_rules! expect {
                ($token:ident, $msg:literal, $self:expr, $diags:expr) => {
                    if let Token::$token = $self.current {
                        $self.advance(false, $diags);
                    } else {
                        $self.error($diags, err![$self, $msg]);
                    }
                };
            }
            #[allow(unused_macros)]
            macro_rules! try_expect {
                ($token:ident, $msg:literal, $self:expr, $diags:expr) => {
                    if let Token::$token = $self.current {
                        $self.advance(false, $diags);
                    } else {
                        if $self.in_ordered_choice {
                            return None;
                        }
                        $self.error($diags, err![$self, $msg]);
                    }
                };
            }

            struct ParserState {
                pos: usize,
                current: Token,
                truncation_mark: MarkTruncation,
                diag_count: usize,
            }
            pub struct Parser<'a> {
                cst: Cst<'a>,
                tokens: Vec<Token>,
                pos: usize,
                current: Token,
                end_of_input: Token,
                max_offset: usize,
                #[allow(dead_code)]
                context: <Self as ParserCallbacks<'a>>::Context,
                error_node: Option<MarkOpened>,
                #[allow(dead_code)]
                in_ordered_choice: bool,
                error_since_advance: bool,
            }
            #[allow(clippy::while_let_loop, dead_code, unused_parens)]
            impl<'a> Parser<'a> {
                fn active_error(&self) -> bool {
                    self.error_node.is_some() || self.error_since_advance
                }
                fn error(
                    &mut self,
                    diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>,
                    diag: <Self as ParserCallbacks<'a>>::Diagnostic
                ) {
                    if self.active_error() {
                        return;
                    }
                    self.error_since_advance = true;
                    diags.push(diag);
                }
                fn advance(&mut self, error: bool, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) {
                    if !error {
                        self.close_error_node(diags);
                        self.error_since_advance = false;
                    }
                    self.cst.data.advance(self.current, false);
                    loop {
                        self.pos += 1;
                        match self.tokens.get(self.pos) {
                            Some(token @ (Token::Error #(#skip_idents)*)) => {
                                self.cst.data.advance(*token, true);
                                continue;
                            }
                            Some(token) if self.predicate_skip(*token) => {
                                self.cst.data.advance(*token, true);
                                continue;
                            }
                            Some(token) => {
                                self.current = *token;
                                break;
                            }
                            None => {
                                self.current = self.end_of_input;
                                break;
                            }
                        }
                    }
                }
                fn is_skipped(token: Token) -> bool {
                    matches!(token, Token::Error #(#skip_idents)*)
                }
                fn init_skip(&mut self) {
                    loop {
                        match self.tokens.get(self.pos) {
                            Some(token @ (Token::Error #(#skip_idents)*)) => {
                                self.pos += 1;
                                self.cst.data.advance(*token, true);
                                continue;
                            }
                            Some(token) if self.predicate_skip(*token) => {
                                self.pos += 1;
                                self.cst.data.advance(*token, true);
                                continue;
                            }
                            Some(token) => {
                                self.current = *token;
                                break;
                            }
                            None => {
                                self.current = self.end_of_input;
                                break;
                            }
                        }
                    }
                }
                fn advance_with_error(
                    &mut self,
                    diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>,
                    diag: <Self as ParserCallbacks<'a>>::Diagnostic
                ) {
                    self.error(diags, diag);
                    if self.error_node.is_none() {
                        self.error_node = Some(self.cst.data.open());
                    }
                    self.advance(true, diags);
                }
                fn peek(&self, lookahead: usize) -> Token {
                    self.tokens
                        .iter()
                        .skip(self.pos)
                        .filter(|token| !Self::is_skipped(**token))
                        .nth(lookahead)
                        .map_or(self.end_of_input, |it| *it)
                }
                fn peek_left(&self, lookbehind: usize) -> Token {
                    self.tokens
                        .iter()
                        .take(self.pos + 1)
                        .rev()
                        .filter(|token| !Self::is_skipped(**token))
                        .nth(lookbehind)
                        .map_or(self.end_of_input, |it| *it)
                }
                fn close_error_node(&mut self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) {
                    if let Some(error_node) = self.error_node {
                        self.cst.data.close(error_node, Rule::Error);
                        self.create_node_error(NodeRef(error_node.0), diags);
                        self.error_node = None;
                    }
                }
                fn open(&mut self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) -> MarkOpened {
                    self.close_error_node(diags);
                    self.cst.data.open()
                }
                fn open_before(&mut self, mark: MarkClosed, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) -> MarkOpened {
                    self.close_error_node(diags);
                    self.cst.data.open_before(mark)
                }
                fn close(&mut self, mark: MarkOpened, rule: Rule, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) -> MarkClosed {
                    self.close_error_node(diags);
                    self.cst.data.close(mark, rule)
                }
                fn close_root(&mut self, mark: MarkOpened, rule: Rule, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) -> MarkClosed {
                    self.close_error_node(diags);
                    self.cst.data.close_root(mark, rule)
                }
                fn mark(&mut self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) -> MarkClosed {
                    self.close_error_node(diags);
                    self.cst.data.mark()
                }
                fn span(&self) -> Span {
                    self.cst.data.spans
                        .get(self.pos)
                        .map_or(self.max_offset..self.max_offset, |span| span.clone())
                }
                fn get_state(&self, diags: &[<Self as ParserCallbacks<'a>>::Diagnostic]) -> ParserState {
                    ParserState {
                        pos: self.pos,
                        current: self.current,
                        truncation_mark: self.cst.data.mark_truncation(),
                        diag_count: diags.len(),
                    }
                }
                fn set_state(
                    &mut self,
                    state: &ParserState,
                    diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>
                ) {
                    self.pos = state.pos;
                    self.current = state.current;
                    diags.truncate(state.diag_count);
                    for i in state.truncation_mark.node_count..self.cst.data.nodes.len() {
                        if let Node::Rule(rule, _) = self.cst.data.nodes[i] {
                            self.delete_node(rule, NodeRef(i));
                        }
                    }
                    self.cst.data.truncate(state.truncation_mark.clone());
                }
                fn create_node(
                    &mut self,
                    rule: Rule,
                    node_ref: NodeRef,
                    diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>
                ) {
                    match rule {
                        #(#create_arms)*
                    }
                }
                fn delete_node(&mut self, _rule: Rule, _node_ref: NodeRef) {
                    #delete_body
                }
                pub fn new_with_context(
                    source: &'a str,
                    diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>,
                    mut context: <Self as ParserCallbacks<'a>>::Context,
                ) -> Parser<'a> {
                    let (tokens, spans) = Self::create_tokens(&mut context, source, diags);
                    let max_offset = source.len();
                    Self {
                        current: Token::EOF,
                        end_of_input: Token::EOF,
                        cst: Cst { data: CstData::new(spans), source },
                        tokens,
                        pos: 0,
                        max_offset,
                        context,
                        error_node: None,
                        in_ordered_choice: false,
                        error_since_advance: false,
                    }
                }
                pub fn new(
                    source: &'a str,
                    diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>,
                ) -> Parser<'a>
                where
                    <Self as ParserCallbacks<'a>>::Context: Default,
                {
                    #[allow(clippy::unit_arg)]
                    Self::new_with_context(source, diags, <Self as ParserCallbacks<'a>>::Context::default())
                }
                fn parse_rule<RuleParser: Fn(&mut Self, &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>)>(
                    mut self,
                    rule: RuleParser,
                    diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>,
                    root: Rule,
                ) -> Cst<'a> {
                    let token_count = self.tokens.len();
                    let m = self.open(diags);
                    self.init_skip();

                    rule(&mut self, diags);

                    self.close_error_node(diags);
                    if self.pos != token_count {
                        self.error(diags, err![self, "invalid syntax, expected: <end of file>"]);
                        let error_tree = self.open(diags);
                        while self.pos < token_count {
                            let token = self.tokens[self.pos];
                            self.cst.data.advance(token, Self::is_skipped(token));
                            self.pos += 1;
                        }
                        self.cst.data.close(error_tree, Rule::Error);
                        self.create_node_error(NodeRef(error_tree.0), diags);
                    }

                    let closed = self.cst.data.close_root(m, root);
                    self.create_node(root, NodeRef(closed.0), diags);
                    self.cst
                }
                pub fn parse(self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) -> Cst<'a> {
                    self.parse_rule(|parser, diags| parser.#start_rule_fn(diags), diags, Rule::#start_rule_variant)
                }
                #(#parts)*
                #(#rules)*
            }

            #callbacks
        }
    }

}
