use crate::VERSION;
use crate::frontend::ast::*;
use crate::frontend::parser::{Cst, NodeRef};
use crate::frontend::sema::*;
use rustc_hash::{FxHashMap, FxHashSet};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::{Result as FmtResult, Write};
use std::path::Path;

pub fn snake_to_pascal_case(name: &str) -> String {
    let mut res = String::new();
    let mut upper = true;
    for c in name.chars() {
        if upper {
            res.push(c.to_ascii_uppercase());
            upper = false;
        } else if c == '_' {
            upper = true;
        } else {
            res.push(c);
        }
    }
    res
}

fn escape(sym: &str) -> String {
    sym.replace(r"\\", r"\")
        .replace(r"\'", "'")
        .escape_default()
        .to_string()
}

trait Generator {
    fn pattern(&self) -> String;
    fn set(&self, open: bool) -> String;
    fn recover(&self) -> String;
}

impl Generator for BTreeSet<TokenName<'_>> {
    fn pattern(&self) -> String {
        let symbols: Vec<_> = self.iter().map(|s| format!("Token::{}", s.0)).collect();
        symbols.join(" | ")
    }
    fn set(&self, open: bool) -> String {
        let set = enum_set_expr(self);
        if open {
            format!("({set} | follow)")
        } else {
            set
        }
    }
    fn recover(&self) -> String {
        format!("({} | recover)", enum_set_expr(self))
    }
}

fn enum_set_expr(set: &BTreeSet<TokenName<'_>>) -> String {
    if set.is_empty() {
        "enumset::EnumSet::empty()".to_string()
    } else {
        let symbols: Vec<_> = set.iter().map(|s| format!("Token::{}", s.0)).collect();
        format!("enumset::enum_set!({})", symbols.join(" | "))
    }
}

fn syntax_error_message(expected: &[String]) -> String {
    let mut msg = if expected.is_empty() {
        "invalid syntax"
    } else if expected.len() == 1 {
        "invalid syntax, expected: "
    } else {
        "invalid syntax, expected one of: "
    }
    .to_string();
    msg.push_str(&expected.join(", "));
    format!("\"{}\"", escape(&msg))
}

/// Parses the generated source and rewrites it with prettyplease. The
/// generator only has to emit valid Rust and does not need to care about
/// indentation or line breaks.
fn format_source(source: &str) -> std::io::Result<String> {
    let syntax = syn::parse_file(source)
        .map_err(|err| std::io::Error::other(format!("invalid generated code: {err}")))?;
    Ok(prettyplease::unparse(&syntax))
}

pub struct RustOutput {}

impl RustOutput {
    pub fn run(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        input: &Path,
        output: &Path,
    ) -> std::io::Result<()> {
        let file = File::cast(cst, NodeRef::ROOT).unwrap();
        let mut generated = String::new();
        Self::output_generated(cst, sema, file, &mut generated)
            .expect("writing to a String cannot fail");
        let generated = format!(
            "// generated by lelwel {VERSION}\n\n{}",
            format_source(&generated)?
        );
        std::fs::write(output.join("generated.rs"), generated)?;

        let parser_path = input.parent().unwrap().join("parser.rs");
        let lexer_path = input.parent().unwrap().join("lexer.rs");
        if !parser_path.exists() && !lexer_path.exists() {
            Self::output_parser(sema, &parser_path)?;
            Self::output_lexer(cst, file, &lexer_path)?;
        }
        Ok(())
    }

    fn output_parser(sema: &SemanticData<'_>, path: &Path) -> std::io::Result<()> {
        let mut callbacks = String::new();
        Self::output_parser_callbacks(&mut callbacks, sema, false, BTreeMap::default())
            .expect("writing to a String cannot fail");
        let callbacks = format_source(&callbacks)?;
        let skeleton = include_str!("../skeleton/parser.rs");
        std::fs::write(path, format!("{skeleton}{callbacks}"))
    }

    fn output_lexer(cst: &Cst<'_>, file: File, path: &Path) -> std::io::Result<()> {
        let mut token_enumerators = "{\n    EOF,\n".to_string();
        for token in file.token_decls(cst) {
            if let Some((symbol, _)) = token.symbol(cst)
                && !(symbol.is_empty()
                    || symbol.starts_with("'<") && symbol.ends_with(">'") && symbol.len() > 4)
            {
                token_enumerators += "    #[token(\"";
                token_enumerators += &symbol[1..symbol.len() - 1];
                token_enumerators += "\")]\n";
            }
            let (name, _) = token.name(cst).unwrap();
            token_enumerators += "    ";
            token_enumerators += name;
            token_enumerators += ",\n";
        }

        let skeleton =
            include_str!("../skeleton/lexer.rs").replace("{\n    EOF,\n", &token_enumerators);
        std::fs::write(path, skeleton)
    }

    fn output_parser_callbacks(
        output: &mut String,
        sema: &SemanticData<'_>,
        is_trait: bool,
        rule_names: BTreeMap<&str, bool>,
    ) -> FmtResult {
        if is_trait {
            output.push_str(
                r#"
                #[allow(clippy::ptr_arg)]
                pub trait ParserCallbacks<'a> {
                    type Diagnostic;
                    type Context;
                    type State: Clone;

                    /// Called at the start of the parse to generate all tokens and corresponding spans.
                    fn create_tokens(context: &mut Self::Context, source: &'a str, diags: &mut Vec<Self::Diagnostic>) -> (Vec<Token>, Vec<Span>);
                    fn lex(&mut self, _expect: enumset::EnumSet<Token>, _diags: &mut Vec<Self::Diagnostic>) -> Option<(Token, Span)> {
                        None
                    }
                    /// Called when diagnostic is created.
                    fn create_diagnostic(&self, span: Span, message: String) -> Self::Diagnostic;

                "#,
            );
        } else {
            output.push_str(
                r#"
                impl<'a> ParserCallbacks<'a> for Parser<'a> {
                    type Diagnostic = Diagnostic;
                    type Context = ();
                    type State = ();

                    fn create_tokens(_context: &mut Self::Context, source: &'a str, diags: &mut Vec<Self::Diagnostic>) -> (Vec<Token>, Vec<Span>) {
                        tokenize(source, diags)
                    }
                    fn create_diagnostic(&self, span: Span, message: String) -> Self::Diagnostic {
                        Self::Diagnostic::error()
                            .with_message(message)
                            .with_label(Label::primary((), span))
                    }
                "#,
            );
        }
        if is_trait {
            for rule_name in rule_names.keys() {
                write!(
                    output,
                    r#"
                    /// Called when `{rule_name}` node is created.
                    fn create_node_{rule_name}(&mut self, _node_ref: NodeRef, _diags: &mut Vec<Self::Diagnostic>) {{}}
                    "#
                )?;
            }
            for (rule_name, in_choice) in rule_names {
                if in_choice {
                    write!(
                        output,
                        r#"
                        /// Called when `{rule_name}` node is deleted during backtracking.
                        fn delete_node_{rule_name}(&mut self, _node_ref: NodeRef) {{}}
                        "#
                    )?;
                }
            }
        }
        let mut predicates = FxHashSet::default();
        for (rule, num) in sema.predicates.values() {
            if predicates.contains(&(rule, num)) {
                continue;
            }
            predicates.insert((rule, num));
            if is_trait {
                write!(
                    output,
                    r#"
                    /// Called when semantic predicate `?{num}` in rule `{rule}` is visited.
                    fn predicate_{rule}_{num}(&self) -> bool;
                    "#
                )?;
            } else {
                write!(
                    output,
                    r#"
                    fn predicate_{rule}_{num}(&self) -> bool {{
                        todo!()
                    }}
                    "#
                )?;
            }
        }
        let mut actions = FxHashSet::default();
        for (rule, num) in sema.actions.values() {
            if actions.contains(&(rule, num)) {
                continue;
            }
            actions.insert((rule, num));
            if is_trait {
                write!(
                    output,
                    r#"
                    /// Called when semantic action `#{num}` in rule `{rule}` is visited.
                    fn action_{rule}_{num}(&mut self, diags: &mut Vec<Self::Diagnostic>);
                    "#
                )?;
            } else {
                write!(
                    output,
                    r#"
                    fn action_{rule}_{num}(&mut self, diags: &mut Vec<Self::Diagnostic>) {{
                        todo!()
                    }}
                    "#
                )?;
            }
        }
        let mut assertions = FxHashSet::default();
        for (rule, num) in sema.assertions.values() {
            if assertions.contains(&(rule, num)) {
                continue;
            }
            assertions.insert((rule, num));
            if is_trait {
                write!(
                    output,
                    r#"
                    /// Called when semantic assertion `!{num}` in rule `{rule}` is visited.
                    fn assertion_{rule}_{num}(&self) -> Option<Self::Diagnostic>;
                    "#
                )?;
            } else {
                write!(
                    output,
                    r#"
                    fn assertion_{rule}_{num}(&self) -> Option<Self::Diagnostic> {{
                        todo!()
                    }}
                    "#
                )?;
            }
        }
        writeln!(output, "}}")
    }

    fn output_node_kind_decl(
        output: &mut String,
        has_rule_rename: bool,
        name: &str,
        is_decl: bool,
    ) -> FmtResult {
        if has_rule_rename {
            writeln!(
                output,
                "{}node_kind = Rule::{};",
                if is_decl { "let mut " } else { "" },
                snake_to_pascal_case(name),
            )?;
        }
        Ok(())
    }

    fn output_cst_close(
        output: &mut String,
        has_rule_rename: bool,
        name: &str,
        assign_lhs: bool,
        parser_name: &str,
        is_start: bool,
    ) -> FmtResult {
        let close = if is_start { "close_root" } else { "close" };
        if has_rule_rename {
            writeln!(
                output,
                "let closed = {parser_name}.{close}(m, node_kind, diags);"
            )?;
            writeln!(
                output,
                "{parser_name}.create_node(node_kind, NodeRef(closed.0), diags);"
            )?;
        } else {
            writeln!(
                output,
                "let closed = {parser_name}.{close}(m, Rule::{}, diags);",
                snake_to_pascal_case(name),
            )?;
            writeln!(
                output,
                "{parser_name}.create_node_{name}(NodeRef(closed.0), diags);"
            )?;
        }
        if assign_lhs {
            writeln!(output, "lhs = closed;")?;
        }
        Ok(())
    }

    fn output_elision_init(
        output: &mut String,
        has_rule_creation: bool,
        parser_name: &str,
        is_start: bool,
        elision: RuleNodeElision,
    ) -> FmtResult {
        if !is_start {
            match elision {
                RuleNodeElision::None => writeln!(output, "let m = {parser_name}.open(diags);")?,
                RuleNodeElision::Conditional => {
                    writeln!(output, "let start = {parser_name}.mark(diags);")?;
                    writeln!(output, "let mut elide = false;")?;
                }
                RuleNodeElision::Unconditional => {
                    if has_rule_creation {
                        writeln!(output, "let start = {parser_name}.mark(diags);")?;
                    }
                }
            }
        }
        Ok(())
    }

    fn output_elision_check(
        output: &mut String,
        has_rule_rename: bool,
        name: &str,
        parser_name: &str,
        is_start: bool,
        elision: RuleNodeElision,
    ) -> FmtResult {
        if !is_start {
            match elision {
                RuleNodeElision::None => {
                    Self::output_cst_close(
                        output,
                        has_rule_rename,
                        name,
                        false,
                        parser_name,
                        is_start,
                    )?;
                }
                RuleNodeElision::Conditional => {
                    writeln!(output, "if !elide {{")?;
                    writeln!(output, "let m = {parser_name}.open_before(start, diags);")?;
                    Self::output_cst_close(
                        output,
                        has_rule_rename,
                        name,
                        false,
                        parser_name,
                        is_start,
                    )?;
                    writeln!(output, "}}")?;
                }
                RuleNodeElision::Unconditional => {}
            }
        }
        Ok(())
    }

    #[allow(clippy::too_many_arguments)]
    fn output_normal_rule(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        output: &mut String,
        has_rule_rename: bool,
        has_rule_creation: bool,
        name: &str,
        regex: Regex,
        is_start: bool,
        elision: RuleNodeElision,
    ) -> FmtResult {
        Self::output_elision_init(output, has_rule_creation, "self", is_start, elision)?;
        if !is_start {
            Self::output_node_kind_decl(output, has_rule_rename, name, true)?;
        }
        Self::output_regex(
            cst,
            sema,
            regex,
            output,
            false,
            name,
            elision,
            "self",
            has_rule_rename,
        )?;
        Self::output_elision_check(output, has_rule_rename, name, "self", is_start, elision)
    }

    #[allow(clippy::too_many_arguments)]
    fn output_left_recursive_rule(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        output: &mut String,
        has_rule_rename: bool,
        name: &str,
        regex: Regex,
        recursive: &RecursiveBranches,
        in_choice: bool,
    ) -> FmtResult {
        // binding power is not required if there is only one recursive branch or
        // if there are only left recursive branches
        let requires_bp = recursive.branches().len() > 1
            && recursive
                .branches()
                .iter()
                .any(|branch| matches!(branch, Recursion::Right(..) | Recursion::LeftRight(..)));
        write!(
            output,
            r#"
            #[allow(unused_variables)]
            fn rec<'a>(
                parser: &mut Parser<'a>,
                follow: enumset::EnumSet<Token>,
                recover: enumset::EnumSet<Token>,
                diags: &mut Vec<<Parser<'a> as ParserCallbacks<'a>>::Diagnostic>,
                {min_bp}
                mut lhs: MarkClosed,
            ) {ret}{{
            "#,
            min_bp = if requires_bp { "min_bp: usize," } else { "" },
            ret = if in_choice { "-> Option<()> " } else { "" },
        )?;
        let call_rec = |parser: &str, binding_power: usize, marker: &str| {
            if requires_bp {
                format!(
                    "rec({parser}, follow, recover, diags, {binding_power}, {marker}){};",
                    if in_choice { "?" } else { "" }
                )
            } else {
                format!(
                    "rec({parser}, follow, recover, diags, {marker}){};",
                    if in_choice { "?" } else { "" }
                )
            }
        };

        // right recursive or non-recursive branches
        Self::output_node_kind_decl(output, has_rule_rename, name, true)?;
        let set =
            sema.predict_sets[&regex.syntax()].set(sema.open_predict.contains(&regex.syntax()));
        writeln!(output, "let expected = {set};")?;
        writeln!(output, "match parser.current(expected, diags) {{")?;
        let ops = if let Regex::Alternation(alt) = regex {
            alt.operands(cst)
        } else {
            unreachable!();
        };
        let mut advance_error_set = BTreeSet::new();
        for alt_op in ops {
            let branch = recursive.get_branch(alt_op);
            if !matches!(branch, None | Some(Recursion::Right(..))) {
                continue;
            }
            let predict = &sema.predict_sets[&alt_op.syntax()];
            let predicate = Self::get_predicate(cst, name, alt_op, "parser");
            let Some(arm) = Self::predict_arm(
                predict,
                sema.open_predict.contains(&alt_op.syntax()),
                &predicate,
            ) else {
                continue;
            };
            advance_error_set = if predicate.is_empty() {
                advance_error_set.difference(predict).cloned().collect()
            } else {
                advance_error_set.union(predict).cloned().collect()
            };
            writeln!(output, "{arm}")?;

            let elision = *sema.elision.get(&alt_op.syntax()).unwrap();
            Self::output_elision_init(output, false, "parser", false, elision)?;

            if let Some(Recursion::Right(_, index)) = branch {
                let binding_power = recursive.binding_power(alt_op).0;
                let Regex::Concat(concat) = alt_op else {
                    unreachable!()
                };
                for (i, concat_op) in concat.operands(cst).enumerate() {
                    if i == index {
                        writeln!(output, "let lhs = parser.mark(diags);")?;
                        writeln!(output, "{}", call_rec("parser", binding_power, "lhs"))?;
                    } else {
                        Self::output_regex(
                            cst,
                            sema,
                            concat_op,
                            output,
                            false,
                            name,
                            elision,
                            "parser",
                            has_rule_rename,
                        )?;
                    }
                }
            } else {
                Self::output_regex(
                    cst,
                    sema,
                    alt_op,
                    output,
                    false,
                    name,
                    elision,
                    "parser",
                    has_rule_rename,
                )?;
            }

            Self::output_elision_check(output, has_rule_rename, name, "parser", false, elision)?;
            writeln!(output, "}}")?;
        }
        if !advance_error_set.is_empty() {
            write!(
                output,
                r#"
                {pattern} => {{
                    parser.advance_with_error(diags, {msg});
                }}
                "#,
                pattern = advance_error_set.pattern(),
                msg = syntax_error_message(&[]),
            )?;
        }
        write!(
            output,
            r#"
                _ => {{
                    parser.error(diags, expected_message(expected));
                }}
            }}
            "#
        )?;

        // left recursive branches
        writeln!(output, "loop {{")?;
        Self::output_node_kind_decl(output, has_rule_rename, name, false)?;
        let set = sema.follow_sets[&regex.syntax()].set(sema.open_follow.contains(&regex.syntax()));
        writeln!(output, "match parser.current({set}, diags) {{")?;
        'branch_loop: for branch in recursive.branches() {
            let (concat, left_index, right_index) = match branch {
                Recursion::Left(Regex::Concat(concat), index) => (concat, *index, None),
                Recursion::LeftRight(Regex::Concat(concat), left_index, right_index) => {
                    (concat, *left_index, Some(*right_index))
                }
                _ => continue,
            };
            let binding_power = recursive.binding_power(branch.regex());
            let mut is_first = true;
            for (i, concat_op) in concat.operands(cst).enumerate() {
                if let Regex::Predicate(..) = concat_op {
                    continue;
                }
                if i == left_index {
                    continue;
                }
                if is_first {
                    is_first = false;
                    let predicate = Self::get_predicate(cst, name, branch.regex(), "parser");
                    let Some(arm) = Self::predict_arm(
                        &sema.predict_sets[&concat_op.syntax()],
                        sema.open_predict.contains(&concat_op.syntax()),
                        &predicate,
                    ) else {
                        continue 'branch_loop;
                    };
                    writeln!(output, "{arm}")?;
                    if requires_bp {
                        let binding_power = binding_power.0;
                        write!(
                            output,
                            r#"
                            if {binding_power} < min_bp {{
                                break;
                            }}
                            "#
                        )?;
                    }
                    writeln!(output, "let m = parser.open_before(lhs, diags);")?;
                }
                if right_index == Some(i) {
                    let binding_power = binding_power.1;
                    writeln!(output, "let rhs = parser.mark(diags);")?;
                    writeln!(output, "{}", call_rec("parser", binding_power, "rhs"))?;
                } else {
                    Self::output_regex(
                        cst,
                        sema,
                        concat_op,
                        output,
                        false,
                        name,
                        RuleNodeElision::None,
                        "parser",
                        has_rule_rename,
                    )?;
                }
            }
            Self::output_cst_close(output, has_rule_rename, name, true, "parser", false)?;
            write!(
                output,
                r#"
                    continue;
                }}
                "#
            )?;
        }
        write!(
            output,
            r#"
                        _ => {{
                            break;
                        }}
                    }}
                }}
                {}
            }}
            let lhs = self.mark(diags);
            "#,
            if in_choice { "Some(())" } else { "" }
        )?;
        writeln!(output, "{}", call_rec("self", 0, "lhs"))
    }

    fn output_parts(cst: &Cst<'_>, rule: RuleDecl, output: &mut String) -> FmtResult {
        let name = rule.name(cst).unwrap().0;
        write!(
            output,
            r#"
            /// Returns the CST for a parse of the {name} rule
            pub fn parse_{name}(mut self, diags: &mut Vec<Diagnostic>) -> Cst<'a> {{
                self.end_of_input = Token::EOF{pascal};
                self.parse_rule(|parser, diags| parser.rule_{name}(enumset::EnumSet::empty(), enumset::EnumSet::empty(), diags), diags, Rule::Part)
            }}
            "#,
            pascal = snake_to_pascal_case(name),
        )
    }

    fn output_rule(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        rule: RuleDecl,
        output: &mut String,
    ) -> FmtResult {
        if !sema.used.contains(&rule.syntax()) {
            // don't generate code for unused rules
            return Ok(());
        }
        let name = rule.name(cst).unwrap().0;
        let recursive = sema.recursive.get(&rule);
        let is_start = sema.start_rule.unwrap() == rule;
        let has_rule_rename = sema.has_rule_rename.contains(&rule);
        let has_rule_creation = sema.has_rule_creation.contains(&rule);
        let elision = if rule.is_elided(cst) {
            &RuleNodeElision::Unconditional
        } else {
            rule.regex(cst)
                .and_then(|regex| sema.elision.get(&regex.syntax()))
                .unwrap_or(&RuleNodeElision::None)
        };
        let in_choice = sema.used_in_ordered_choice.contains(&rule.syntax());

        if has_rule_rename {
            writeln!(output, "#[allow(unused_assignments)]")?;
        }
        writeln!(output, "#[allow(unused_variables)]")?;
        write!(
            output,
            "fn rule_{name}(&mut self, follow: enumset::EnumSet<Token>, recover: enumset::EnumSet<Token>, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) "
        )?;
        if in_choice {
            write!(output, "-> Option<()> ")?;
        }
        writeln!(output, "{{")?;
        if let Some(regex) = rule.regex(cst) {
            if recursive.is_some_and(|recursive| {
                recursive
                    .branches()
                    .iter()
                    .any(|rec| matches!(rec, Recursion::Left(..) | Recursion::LeftRight(..)))
            }) {
                Self::output_left_recursive_rule(
                    cst,
                    sema,
                    output,
                    has_rule_rename,
                    name,
                    regex,
                    recursive.unwrap(),
                    in_choice,
                )?;
            } else {
                Self::output_normal_rule(
                    cst,
                    sema,
                    output,
                    has_rule_rename,
                    has_rule_creation,
                    name,
                    regex,
                    is_start,
                    *elision,
                )?;
            }
        }
        if in_choice {
            writeln!(output, "Some(())")?;
        }
        writeln!(output, "}}")
    }

    fn get_predicate(cst: &Cst<'_>, rule_name: &str, regex: Regex, parser_name: &str) -> String {
        match regex {
            Regex::Concat(concat) => match concat.operands(cst).next().unwrap() {
                Regex::Predicate(pred) => {
                    if pred.is_true(cst) {
                        " if true".to_string()
                    } else {
                        format!(
                            " if {parser_name}.predicate_{rule_name}_{}()",
                            &pred.value(cst).unwrap().0[1..]
                        )
                    }
                }
                _ => "".to_string(),
            },
            Regex::Paren(paren) => {
                if let Some(inner) = paren.inner(cst) {
                    Self::get_predicate(cst, rule_name, inner, parser_name)
                } else {
                    "".to_string()
                }
            }
            _ => "".to_string(),
        }
    }

    /// Returns the match-arm prefix for a branch selected by `predict`, or
    /// `None` when the branch can never be selected (empty set, closed
    /// follow). An open (nullable) branch selects via a guard against
    /// `set | follow` instead of a static token pattern.
    fn predict_arm(
        predict: &BTreeSet<TokenName<'_>>,
        open: bool,
        predicate: &str,
    ) -> Option<String> {
        if predict.is_empty() && !open {
            return None;
        }
        Some(if open {
            let suffix = predicate
                .strip_prefix(" if ")
                .map(|s| format!(" && {s}"))
                .unwrap_or_default();
            format!("c if {}.contains(c){suffix} => {{", predict.set(true))
        } else {
            format!("{}{predicate} => {{", predict.pattern())
        })
    }

    /// Returns the early return for a branch of an ordered choice, or an empty
    /// string when the regex is not part of an ordered choice.
    fn ordered_choice_return(parser_name: &str, in_choice: bool) -> String {
        if in_choice {
            format!(
                r#"
                if {parser_name}.in_ordered_choice {{
                    return None;
                }}
                "#
            )
        } else {
            String::new()
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn output_recovering_operation(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        regex: Regex,
        output: &mut String,
        open_before: bool,
        rule_name: &str,
        rule_elision: RuleNodeElision,
        parser_name: &str,
        has_rule_rename: bool,
        op: Regex,
        in_choice: bool,
        is_loop: bool,
    ) -> FmtResult {
        let expected = if is_loop {
            &sema.follow_sets[&op.syntax()]
        } else {
            &sema.predict_sets[&regex.syntax()]
        };

        let set = expected.set(if is_loop {
            sema.open_follow.contains(&op.syntax())
        } else {
            sema.open_predict.contains(&regex.syntax())
        });
        write!(
            output,
            r#"
            let expected = {set};
            loop {{
                match {parser_name}.current(expected, diags) {{
                    {first}{predicate} => {{
            "#,
            first = sema.first_sets[&op.syntax()].pattern(),
            predicate = Self::get_predicate(cst, rule_name, op, parser_name),
        )?;
        if open_before {
            write!(
                output,
                r#"
                if m.is_none() {{
                    m = Some({parser_name}.open_before(lhs, diags));
                }}
                "#
            )?;
        }
        Self::output_regex(
            cst,
            sema,
            op,
            output,
            false,
            rule_name,
            rule_elision,
            parser_name,
            has_rule_rename,
        )?;
        if !is_loop {
            writeln!(output, "break;")?;
        }
        writeln!(output, "}}")?;

        let follow =
            sema.follow_sets[&regex.syntax()].set(sema.open_follow.contains(&regex.syntax()));
        let recovery = sema.recovery_sets[&regex.syntax()].recover();
        write!(
            output,
            r#"
                    c if {follow}.contains(c) => break,
                    c if {recovery}.contains(c) => {{
                        {ordered_choice_return}{parser_name}.error(diags, expected_message(expected));
                        break;
                    }}
                    _ => {{
                        {ordered_choice_return}{parser_name}.advance_with_error(diags, expected_message(expected));
                    }}
                }}
            }}
            "#,
            ordered_choice_return = Self::ordered_choice_return(parser_name, in_choice),
        )
    }

    #[allow(clippy::too_many_arguments)]
    fn output_regex(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        regex: Regex,
        output: &mut String,
        open_before: bool,
        rule_name: &str,
        rule_elision: RuleNodeElision,
        parser_name: &str,
        has_rule_rename: bool,
    ) -> FmtResult {
        let in_choice = sema.used_in_ordered_choice.contains(&regex.syntax());
        let expect_macro = if in_choice { "try_expect!" } else { "expect!" };
        match regex {
            Regex::Name(name) => {
                let decl = sema.decl_bindings[&name.syntax()];
                if let Some(rule) = RuleDecl::cast(cst, decl) {
                    let name = rule.name(cst).unwrap().0;
                    let rule_in_choice = sema.used_in_ordered_choice.contains(&rule.syntax());
                    let follow = sema.follow_sets[&regex.syntax()]
                        .set(sema.open_follow.contains(&regex.syntax()));
                    let recover = sema.follow_sets[&regex.syntax()].recover();
                    writeln!(
                        output,
                        "{parser_name}.rule_{name}({follow}, {recover}, diags){};",
                        if rule_in_choice && in_choice { "?" } else { "" }
                    )?;
                } else if let Some(token) = TokenDecl::cast(cst, decl) {
                    let name = token.name(cst).unwrap().0;
                    let sym = token
                        .symbol(cst)
                        .map_or(name, |(sym, _)| &sym[1..sym.len() - 1]);
                    writeln!(
                        output,
                        "{expect_macro}({name}, {}, {parser_name}, diags);",
                        syntax_error_message(&[sym.to_string()])
                    )?;
                }
            }
            Regex::Symbol(sym) => {
                let decl = sema.decl_bindings[&sym.syntax()];
                if let Some(token) = TokenDecl::cast(cst, decl) {
                    let name = token.name(cst).unwrap().0;
                    let sym = token.symbol(cst).unwrap().0;
                    writeln!(
                        output,
                        "{expect_macro}({name}, {}, {parser_name}, diags);",
                        syntax_error_message(&[sym.to_string()])
                    )?;
                }
            }
            Regex::OrderedChoice(choice) => {
                write!(
                    output,
                    r#"
                    {parser_name}.in_ordered_choice = true;
                    'ordered_choice: {{
                        let state = {parser_name}.get_state(diags);
                    "#
                )?;
                if rule_elision == RuleNodeElision::Conditional {
                    writeln!(output, "let elision_state = elide;")?;
                }
                if has_rule_rename {
                    writeln!(output, "let node_kind_state = node_kind;")?;
                }
                let ops = choice.operands(cst).collect::<Vec<_>>();
                for op in &ops[..ops.len() - 1] {
                    let predict = &sema.predict_sets[&op.syntax()];
                    let open = sema.open_predict.contains(&op.syntax());
                    if predict.is_empty() && !open {
                        continue;
                    }
                    if open {
                        writeln!(output, "let expected = {};", predict.set(true))?;
                        writeln!(
                            output,
                            "if expected.contains({parser_name}.current(expected, diags)) {{"
                        )?;
                    } else {
                        writeln!(
                            output,
                            "if matches!({parser_name}.current({}, diags), {}) {{",
                            predict.set(false),
                            predict.pattern()
                        )?;
                    }

                    writeln!(output, "if (|| {{")?;
                    Self::output_regex(
                        cst,
                        sema,
                        *op,
                        output,
                        false,
                        rule_name,
                        rule_elision,
                        parser_name,
                        has_rule_rename,
                    )?;
                    write!(
                        output,
                        r#"
                        Some(())
                        }})().is_some() {{
                            break 'ordered_choice;
                        }}
                        {parser_name}.set_state(&state, diags);
                        "#
                    )?;
                    if rule_elision == RuleNodeElision::Conditional {
                        writeln!(output, "elide = elision_state;")?;
                    }
                    if has_rule_rename {
                        writeln!(output, "node_kind = node_kind_state;")?;
                    }
                    writeln!(output, "}}")?;
                }
                writeln!(output, "{parser_name}.in_ordered_choice = false;")?;

                let op = *ops.last().unwrap();
                let predict = &sema.predict_sets[&op.syntax()];
                let open = sema.open_predict.contains(&op.syntax());
                if predict.is_empty() && !open {
                    writeln!(
                        output,
                        "{parser_name}.advance_with_error(diags, {});",
                        syntax_error_message(&[])
                    )?;
                } else {
                    if open {
                        writeln!(output, "let expected = {};", predict.set(true))?;
                        writeln!(
                            output,
                            "if expected.contains({parser_name}.current(expected, diags)) {{"
                        )?;
                    } else {
                        writeln!(
                            output,
                            "if matches!({parser_name}.current({}, diags), {}) {{",
                            predict.set(false),
                            predict.pattern()
                        )?;
                    }
                    Self::output_regex(
                        cst,
                        sema,
                        op,
                        output,
                        false,
                        rule_name,
                        rule_elision,
                        parser_name,
                        has_rule_rename,
                    )?;
                    write!(
                        output,
                        r#"
                        }} else {{
                            {parser_name}.advance_with_error(diags, {msg});
                        }}
                        "#,
                        msg = syntax_error_message(&[]),
                    )?;
                }
                writeln!(output, "}}")?;
            }
            Regex::Concat(concat) => {
                for op in concat.operands(cst) {
                    Self::output_regex(
                        cst,
                        sema,
                        op,
                        output,
                        false,
                        rule_name,
                        rule_elision,
                        parser_name,
                        has_rule_rename,
                    )?;
                }
            }
            Regex::Alternation(alt) => {
                let set = sema.predict_sets[&regex.syntax()]
                    .set(sema.open_predict.contains(&regex.syntax()));
                writeln!(output, "let expected = {set};")?;
                writeln!(output, "match {parser_name}.current(expected, diags) {{")?;
                let mut advance_error_set = BTreeSet::new();
                for op in alt.operands(cst) {
                    let predict = &sema.predict_sets[&op.syntax()];
                    let predicate = Self::get_predicate(cst, rule_name, op, parser_name);
                    let Some(arm) = Self::predict_arm(
                        predict,
                        sema.open_predict.contains(&op.syntax()),
                        &predicate,
                    ) else {
                        continue;
                    };
                    advance_error_set = if predicate.is_empty() {
                        advance_error_set.difference(predict).cloned().collect()
                    } else {
                        advance_error_set.union(predict).cloned().collect()
                    };
                    writeln!(output, "{arm}")?;
                    Self::output_regex(
                        cst,
                        sema,
                        op,
                        output,
                        false,
                        rule_name,
                        rule_elision,
                        parser_name,
                        has_rule_rename,
                    )?;
                    writeln!(output, "}}")?;
                }
                if !advance_error_set.is_empty() {
                    write!(
                        output,
                        r#"
                        {pattern} => {{
                            {ordered_choice_return}{parser_name}.advance_with_error(diags, {msg});
                        }}
                        "#,
                        pattern = advance_error_set.pattern(),
                        msg = syntax_error_message(&[]),
                        ordered_choice_return = Self::ordered_choice_return(parser_name, in_choice),
                    )?;
                }
                write!(
                    output,
                    r#"
                        _ => {{
                            {ordered_choice_return}{parser_name}.error(diags, expected_message(expected));
                        }}
                    }}
                    "#,
                    ordered_choice_return = Self::ordered_choice_return(parser_name, in_choice),
                )?;
            }
            Regex::Star(star) => {
                Self::output_recovering_operation(
                    cst,
                    sema,
                    regex,
                    output,
                    open_before,
                    rule_name,
                    rule_elision,
                    parser_name,
                    has_rule_rename,
                    star.operand(cst).unwrap(),
                    in_choice,
                    true,
                )?;
            }
            Regex::Plus(plus) => {
                let op = plus.operand(cst).unwrap();
                Self::output_regex(
                    cst,
                    sema,
                    op,
                    output,
                    false,
                    rule_name,
                    rule_elision,
                    parser_name,
                    has_rule_rename,
                )?;
                Self::output_recovering_operation(
                    cst,
                    sema,
                    regex,
                    output,
                    open_before,
                    rule_name,
                    rule_elision,
                    parser_name,
                    has_rule_rename,
                    op,
                    in_choice,
                    true,
                )?;
            }
            Regex::Optional(opt) => {
                Self::output_recovering_operation(
                    cst,
                    sema,
                    regex,
                    output,
                    open_before,
                    rule_name,
                    rule_elision,
                    parser_name,
                    has_rule_rename,
                    opt.operand(cst).unwrap(),
                    in_choice,
                    false,
                )?;
            }
            Regex::Paren(paren) => {
                if let Some(inner) = paren.inner(cst) {
                    Self::output_regex(
                        cst,
                        sema,
                        inner,
                        output,
                        false,
                        rule_name,
                        rule_elision,
                        parser_name,
                        has_rule_rename,
                    )?;
                }
            }
            Regex::Action(action) => {
                writeln!(
                    output,
                    "{parser_name}.action_{rule_name}_{}(diags);",
                    &action.value(cst).unwrap().0[1..]
                )?;
            }
            Regex::Assertion(assertion) => {
                write!(
                    output,
                    r#"
                    if let Some(diag) = {parser_name}.assertion_{rule_name}_{}() {{
                        {ordered_choice_return}{parser_name}.error_since_advance = true;
                        diags.push(diag);
                    }}
                    "#,
                    &assertion.value(cst).unwrap().0[1..],
                    ordered_choice_return = Self::ordered_choice_return(parser_name, in_choice),
                )?;
            }
            Regex::NodeRename(rename) => {
                let name = &rename.value(cst).unwrap().0[1..];
                if !name.is_empty() {
                    writeln!(output, "node_kind = Rule::{};", snake_to_pascal_case(name))?;
                }
            }
            Regex::NodeElision(_) => {
                if rule_elision == RuleNodeElision::Conditional {
                    writeln!(output, "elide = true;")?;
                }
            }
            Regex::NodeMarker(marker) => {
                let number = marker.number(cst);
                writeln!(output, "let m{number} = {parser_name}.mark(diags);")?;
            }
            Regex::NodeCreation(creation) => {
                let node_name = creation.node_name(cst).unwrap_or(rule_name);
                let mark = if creation.whole_rule(cst) {
                    "start".to_string()
                } else {
                    format!("m{}", creation.number(cst).unwrap())
                };
                write!(
                    output,
                    r#"
                    let open_node = {parser_name}.open_before({mark}, diags);
                    let closed = {parser_name}.close(open_node, Rule::{node_kind}, diags);
                    {parser_name}.create_node_{node_name}(NodeRef(closed.0), diags);
                    "#,
                    node_kind = snake_to_pascal_case(node_name),
                )?;
            }
            Regex::Commit(_) => {
                writeln!(output, "{parser_name}.in_ordered_choice = false;")?;
            }
            Regex::Return(_) => {
                let ret = if in_choice { " None" } else { "" };
                match rule_elision {
                    RuleNodeElision::None => write!(
                        output,
                        r#"
                        if {parser_name}.active_error() {{
                            let closed = {parser_name}.close(m, Rule::Error, diags);
                            {parser_name}.create_node_error(NodeRef(closed.0), diags);
                            return{ret};
                        }}
                        "#
                    )?,
                    RuleNodeElision::Conditional => write!(
                        output,
                        r#"
                        if {parser_name}.active_error() {{
                            if !elide {{
                                let m = {parser_name}.open_before(start, diags);
                                let closed = {parser_name}.close(m, Rule::Error, diags);
                                {parser_name}.create_node_error(NodeRef(closed.0), diags);
                            }}
                            return{ret};
                        }}
                        "#
                    )?,
                    RuleNodeElision::Unconditional => write!(
                        output,
                        r#"
                        if {parser_name}.active_error() {{
                            return{ret};
                        }}
                        "#
                    )?,
                }
            }
            Regex::Predicate(_) => {}
        }
        Ok(())
    }

    /// Outputs the Parser struct and impl.
    fn output_generated(
        cst: &Cst<'_>,
        sema: &SemanticData<'_>,
        file: File,
        output: &mut String,
    ) -> FmtResult {
        let mut token_symbols = FxHashMap::from_iter([("EOF", "<end of file>")]);
        for token in file.token_decls(cst) {
            let name = token.name(cst).unwrap().0;
            let sym = token
                .symbol(cst)
                .map_or(name, |(sym, _)| &sym[1..sym.len() - 1]);
            token_symbols.insert(name, sym);
        }
        let contains_ordered_choice = !sema.used_in_ordered_choice.is_empty();
        let mut rule_names = BTreeMap::from_iter([("error", contains_ordered_choice)]);
        if !sema.parts.is_empty() {
            rule_names.insert("part", false);
        }
        for rule in file.rule_decls(cst) {
            let in_choice = sema.used_in_ordered_choice.contains(&rule.syntax());
            rule_names
                .entry(rule.name(cst).unwrap().0)
                .and_modify(|val| *val |= in_choice)
                .or_insert(in_choice);
        }
        for (rule_name, node_refs) in sema.rule_bindings.iter() {
            let in_choice = node_refs.iter().fold(false, |acc, node_ref| {
                acc | sema.used_in_ordered_choice.contains(node_ref)
            });
            rule_names
                .entry(rule_name)
                .and_modify(|val| *val |= in_choice)
                .or_insert(in_choice);
        }

        output.push_str(
            r#"
            #[derive(Copy, Clone, PartialEq, Eq)]
            #[allow(dead_code)]
            pub enum Rule {
            "#,
        );
        for rule_name in rule_names.keys() {
            writeln!(output, "{},", snake_to_pascal_case(rule_name))?;
        }
        output.push_str(
            r#"
            }
            impl std::fmt::Debug for Rule {
                fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                    match self {
            "#,
        );
        for rule_name in rule_names.keys() {
            writeln!(
                output,
                "Rule::{} => write!(f, {rule_name:?}),",
                snake_to_pascal_case(rule_name)
            )?;
        }
        output.push_str(
            r#"
                    }
                }
            }
            "#,
        );

        output.push_str(include_str!("../skeleton/generated.rs"));

        let mut skip = String::new();
        for token in sema.skipped.iter() {
            skip += " | Token::";
            skip += token.name(cst).unwrap().0;
        }

        let start_rule = sema.start_rule.unwrap().name(cst).unwrap().0;
        let start_rule_pascal_case = snake_to_pascal_case(start_rule);

        write!(
            output,
            r#"
            #[allow(clippy::while_let_loop, dead_code, unused_parens)]
            impl<'a> Parser<'a> {{
                fn is_skipped(token: Token) -> bool {{
                    matches!(token, Token::Error{skip})
                }}
                fn create_node(&mut self, rule: Rule, node_ref: NodeRef, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) {{
                    match rule {{
            "#
        )?;
        for rule_name in rule_names.keys() {
            writeln!(
                output,
                "Rule::{} => self.create_node_{rule_name}(node_ref, diags),",
                snake_to_pascal_case(rule_name)
            )?;
        }
        write!(
            output,
            r#"
                    }}
                }}
                fn delete_node(&mut self, _rule: Rule, _node_ref: NodeRef) {{
            "#
        )?;
        if contains_ordered_choice {
            let delete_covered = rule_names.values().all(|in_choice| *in_choice);
            writeln!(output, "match _rule {{")?;
            for (rule_name, in_choice) in rule_names.iter() {
                if *in_choice {
                    writeln!(
                        output,
                        "Rule::{} => self.delete_node_{rule_name}(_node_ref),",
                        snake_to_pascal_case(rule_name)
                    )?;
                }
            }
            if !delete_covered {
                writeln!(output, "_ => {{}}")?;
            }
            writeln!(output, "}}")?;
        }
        write!(
            output,
            r#"
            }}
            /// Returns the CST for a parse of the start rule
            pub fn parse(self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) -> Cst<'a> {{
                self.parse_rule(|parser, diags| parser.rule_{start_rule}(enumset::EnumSet::empty(), enumset::EnumSet::empty(), diags), diags, Rule::{start_rule_pascal_case})
            }}
            "#
        )?;
        for rule in sema.parts.iter() {
            Self::output_parts(cst, *rule, output)?;
        }
        for rule in file.rule_decls(cst) {
            Self::output_rule(cst, sema, rule, output)?;
        }
        writeln!(output, "}}")?;

        // Runtime token symbols and message builder, in token-name order so
        // the generated messages are deterministic.
        let mut symbols: Vec<(String, String)> = token_symbols
            .iter()
            .map(|(name, symbol)| (name.to_string(), symbol.to_string()))
            .collect();
        for part in sema.parts.iter() {
            let name = part.name(cst).unwrap().0;
            symbols.push((
                format!("EOF{}", snake_to_pascal_case(name)),
                "<end of file>".to_string(),
            ));
        }
        symbols.sort();
        output.push_str(
            r#"
            #[allow(dead_code)]
            const TOKEN_SYMBOLS: &[(Token, &str)] = &[
            "#,
        );
        for (name, symbol) in &symbols {
            writeln!(output, "(Token::{name}, {symbol:?}),")?;
        }
        output.push_str(
            r#"
            ];
            "#,
        );

        Self::output_parser_callbacks(output, sema, true, rule_names)
    }
}
